export const QuerysConfiguracion = {
  getConfiguracion: [
    `
    IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'RipCaja')
    BEGIN
      EXEC('CREATE SCHEMA [RipCaja]')
    END
    `,
    `
    IF NOT EXISTS (SELECT * FROM sys.objects 
    WHERE object_id = OBJECT_ID(N'[RipCaja].[RIP_CONFIGURACIONCUENTAS]') 
    AND type in (N'U'))
    BEGIN
      CREATE TABLE [RipCaja].[RIP_CONFIGURACIONCUENTAS](
        [SOBRANTEVENTA] [nvarchar](20) NULL,
        [FALTANTEVENTA] [nvarchar](20) NULL,
        [SOBRANTEREDONDEO] [nvarchar](20) NULL,
        [FALTANTEREDONDEO] [nvarchar](20) NULL,
        [IVA] [nvarchar](20) NULL,
        [COMISIONBANCARIA] [nvarchar](20) NULL,
        [RAIZPAGARE] [nvarchar](20) NULL,
        [RAIZUTILIDAD] [nvarchar](20) NULL,
        [APERTURA] [nchar](10) NULL
      ) ON [PRIMARY]
    END
    `,
    `
    IF NOT EXISTS (SELECT * FROM sys.objects 
    WHERE object_id = OBJECT_ID(N'[RipCaja].[RIP_PERMISOSUSUARIOS]') 
    AND type in (N'U'))
    BEGIN
      CREATE TABLE [RipCaja].[RIP_PERMISOSUSUARIOS](
        [CODUSUARIO] [int] NOT NULL,
        [VISUALIZARPAGARES] [int] NOT NULL,
        [VISUALIZARCAJAS] [int] NOT NULL,
        [VISUALIZARREPORTES] [int] NOT NULL,
        [DESCONTABILIZAR] [int] NOT NULL,
        [CONTABILIZAR] [nvarchar](1) NULL,
        [REGISTRARPAGARES] [nvarchar](1) NULL,
        [VISUALIZARCONFIGURACION] [int] NULL,
        [VISUALIZARTRANSFERENCIAS] [int] NULL,
        [VISUALIZARVENTAS] [int] NULL,
        [VISUALIZARBALANCES] [int] NULL,
        [VISUALIZARDETALLEBANCO] [int] NULL
      ) ON [PRIMARY]
    END
    `,
    `
    ALTER TABLE [RipCaja].[RIP_PERMISOSUSUARIOS] ADD DEFAULT ((1)) FOR [VISUALIZARPAGARES]
    `,
    `
    ALTER TABLE [RipCaja].[RIP_PERMISOSUSUARIOS] ADD DEFAULT ((1)) FOR [VISUALIZARCAJAS]
    `,
    `
    ALTER TABLE [RipCaja].[RIP_PERMISOSUSUARIOS] ADD DEFAULT ((1)) FOR [VISUALIZARREPORTES]
    `,
    `
    ALTER TABLE [RipCaja].[RIP_PERMISOSUSUARIOS] ADD DEFAULT ((1)) FOR [DESCONTABILIZAR]
    `,
    `
    ALTER TABLE [RipCaja].[RIP_PERMISOSUSUARIOS] ADD DEFAULT ((1)) FOR [CONTABILIZAR]
    `,
    `
    ALTER TABLE [RipCaja].[RIP_PERMISOSUSUARIOS] ADD DEFAULT ((0)) FOR [REGISTRARPAGARES]
    `,
    `
    ALTER TABLE [RipCaja].[RIP_PERMISOSUSUARIOS] ADD DEFAULT ((0)) FOR [VISUALIZARCONFIGURACION]
    `,
    `
    ALTER TABLE [RipCaja].[RIP_PERMISOSUSUARIOS] ADD DEFAULT ((0)) FOR [VISUALIZARTRANSFERENCIAS]
    `,
    `
    ALTER TABLE [RipCaja].[RIP_PERMISOSUSUARIOS] ADD DEFAULT ((0)) FOR [VISUALIZARVENTAS]
    `,
    `
    ALTER TABLE [RipCaja].[RIP_PERMISOSUSUARIOS] ADD DEFAULT ((0)) FOR [VISUALIZARBALANCES]
    `
  ],
  getConfiguracionEmpresas:[
    `
    IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'RipCaja')
    BEGIN
      EXEC('CREATE SCHEMA [RipCaja]')
    END
    `,
    `
    IF NOT EXISTS (SELECT * FROM sys.objects
				WHERE object_id = OBJECT_ID(N'[dbo].[RIPV_DECLARADOZ]') 
				AND type in (N'V'))
      BEGIN 
        EXEC ('
            CREATE VIEW [dbo].[RIPV_DECLARADOZ] AS
              SELECT 
                DZ.TIPO
                , DZ.CAJA
                , DZ.NUMZ
                , DZ.CODMONEDA
                , ISNULL(COTI.COTIZACION,1)*IMPORTE IMPORTE
                , DZ.CODMEDIOPAGO
                , DZ.OBSERVACIONES
                , DZ.IDMOTIVO
                , DZ.AUTO
                , DZ.DESCUADRE

              FROM
                ARQUEOS ARQ  WITH (NOLOCK)
                INNER JOIN DECLARADOZ DZ  WITH (NOLOCK) ON DZ.CAJA=ARQ.CAJA AND DZ.NUMZ=ARQ.NUMERO AND ARQ.ARQUEO=''Z''
                LEFT JOIN COTIZACIONES COTI  WITH (NOLOCK) ON DZ.CODMONEDA=COTI.CODMONEDA AND ARQ.FECHA=COTI.FECHA
          ')
      END 

    `,
    `
    IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RIP_FORMASPAGOS]') 
				AND type in (N'U')) 
      BEGIN
        CREATE TABLE [dbo].[RIP_FORMASPAGOS](
          [ID] [int] IDENTITY(1,1) NOT NULL,
          [DESCRIPCION] [nvarchar](100) NOT NULL
        ) ON [PRIMARY]
      END
      
    `, 
    `
    IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RIP_RELACIONFORMASPAGO]') 
				AND type in (N'U')) 
      BEGIN
       CREATE TABLE [dbo].[RIP_RELACIONFORMASPAGO](
          [CODFORMAPAGO] [nvarchar](6) NULL,
          [IDFORMAPAGO] [int] NULL
        ) ON [PRIMARY]
      END
      
    `,
    `
    IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[RipCaja].[PROC_GETCOTIZACION]') AND type in(N'P'))
	BEGIN
	  EXEC ('
        CREATE PROCEDURE [rip].[PROC_GETCOTIZACION](@FECHA AS DATE , @IMPORTE AS FLOAT=1) AS SET NOCOUNT ON
            DECLARE 
              @MONEDA_VES AS INT =4
              , @MONEDA_USD AS INT=2
              , @MONEDA_EUR AS INT=3

            DECLARE
              @ISO_MONEDA_VES AS NVARCHAR(3)=(SELECT M.CODIGOISO FROM MONEDAS M WHERE M.CODMONEDA=@MONEDA_VES)
              , @ISO_MONEDA_USD AS NVARCHAR(3)=(SELECT M.CODIGOISO FROM MONEDAS M WHERE M.CODMONEDA=@MONEDA_USD)
              , @ISO_MONEDA_EUR AS NVARCHAR(3)=(SELECT M.CODIGOISO FROM MONEDAS M WHERE M.CODMONEDA=@MONEDA_EUR)

            --PRIMERO DE BS A TODAS LAS MONEDAS
            SELECT FORMAT(@IMPORTE,''n'',''es-VE'')+'' ''+ @ISO_MONEDA_VES+'' = ''+FORMAT(@IMPORTE/dbo.F_GET_COTIZACION(@FECHA, @MONEDA_VES),''n'',''es-VE'')+'' ''+@ISO_MONEDA_USD MENSAJE
            UNION ALL
            SELECT FORMAT(@IMPORTE,''n'',''es-VE'')+'' ''+ @ISO_MONEDA_VES+'' = ''+FORMAT(@IMPORTE/dbo.F_GET_COTIZACION(@FECHA, @MONEDA_VES)*1/dbo.F_GET_COTIZACION(@FECHA, @MONEDA_EUR),''n'',''es-VE'')+'' ''+@ISO_MONEDA_EUR MENSAJE
            --AHORA DE USD AL RESTO
            UNION ALL
            SELECT FORMAT(@IMPORTE,''n'',''es-VE'')+'' ''+ @ISO_MONEDA_USD+'' = ''+FORMAT(@IMPORTE*dbo.F_GET_COTIZACION(@FECHA, @MONEDA_VES),''n'',''es-VE'')+'' ''+@ISO_MONEDA_VES MENSAJE
            UNION ALL
            SELECT FORMAT(@IMPORTE,''n'',''es-VE'')+'' ''+ @ISO_MONEDA_USD+'' = ''+FORMAT(@IMPORTE*1/dbo.F_GET_COTIZACION(@FECHA, @MONEDA_EUR),''n'',''es-VE'')+'' ''+@ISO_MONEDA_EUR MENSAJE
            --AHORA DE EUROS AL RESTO
            --AHORA DE USD AL RESTO
            UNION ALL
            SELECT FORMAT(@IMPORTE,''n'',''es-VE'')+'' ''+ @ISO_MONEDA_EUR+'' = ''+FORMAT(@IMPORTE*dbo.F_GET_COTIZACION(@FECHA, @MONEDA_EUR)*dbo.F_GET_COTIZACION(@FECHA, @MONEDA_VES),''n'',''es-VE'')+'' ''+@ISO_MONEDA_VES MENSAJE
            UNION ALL
            SELECT FORMAT(@IMPORTE,''n'',''es-VE'')+'' ''+ @ISO_MONEDA_EUR+'' = ''+FORMAT(@IMPORTE*dbo.F_GET_COTIZACION(@FECHA, @MONEDA_EUR),''n'',''es-VE'')+'' ''+@ISO_MONEDA_USD MENSAJE
	')
	END

    `,
    `
    IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[RipCaja].[RIP_DIFERENCIAFRONT_WEB]') AND type in(N'IF'))
	BEGIN
	EXEC ('
	CREATE FUNCTION [RipCaja].[RIP_DIFERENCIAFRONT_WEB](@FECHA AS DATETIME, @CAJA AS NVARCHAR(4) ) RETURNS TABLE
AS RETURN (
SELECT CAJA, FECHA,  Z, CODFORMAPAGO, DESCRIPCION,
	IMPORTE,  IMPORTE*dbo.F_GET_COTIZACION(@FECHA,4) IMPORTE_LOCAL, DECLARADO, DECLARADO*dbo.F_GET_COTIZACION(@FECHA,4) DECLARADO_LOCAL, 
		GASTOS, SERIECAJA, FO, CERRADO, ROUND(ROUND(CAST(IMPORTE AS FLOAT),2)-ROUND(CAST(DECLARADO AS FLOAT),2),2) DIFERENCIA, CODMONEDA, dbo.F_GET_COTIZACION(@FECHA,4) TASA_VES,OBSERVACION FROM (
SELECT  --FP.CODFORMAPAGO, FP.DESCRIPCION, S.SERIE SERIECAJA, S.DESCRIPCION CAJA, ARQ.NUMERO 
	ARQ.FECHA
	, S.DESCRIPCION CAJA
	, ARQ.NUMERO Z
	, FP.CODFORMAPAGO
	, FP.DESCRIPCION+'' (''+M.CODIGOISO+'')'' COLLATE Modern_Spanish_CI_AS DESCRIPCION
	, ISNULL((SELECT 
		SUM(T.IMPORTE*T.FACTORMONEDA)
		FROM
			FACTURASVENTA FV WITH(NOLOCK)
			INNER JOIN TESORERIA T WITH(NOLOCK) ON FV.NUMSERIE=T.SERIE AND FV.NUMFACTURA=T.NUMERO AND FV.N=T.N
		WHERE
			T.ORIGEN IN (''C'')
			AND T.TIPODOCUMENTO IN (''F'')
			AND T.SERIE LIKE ARQ.CAJA+''%''
			AND (FV.Z=ARQ.NUMERO)
			AND T.CODFORMAPAGO=FP.CODFORMAPAGO
			AND T.FECHADOCUMENTO=@FECHA
		GROUP BY 
			T.FECHADOCUMENTO, SUBSTRING(T.SERIE,1,3)),0) IMPORTE
	, ISNULL((SELECT SUM(DZ.IMPORTE*V.PORCENTAJE/100) 
		 + ISNULL((SELECT TOP 1 SUM(CASE TIPOMOVCAJA WHEN 4 THEN IMPORTE*-1 ELSE IMPORTE END) IMPORTE 
				FROM PAGOS FC WHERE FC.CODCONCEPTOPAGO=-1 AND FC.TIPOMOVCAJA IN (1,2,3) AND FC.Z=ARQ.NUMERO AND FC.CAJA=ARQ.CAJA AND DZ.CODMEDIOPAGO= ''1''
			 GROUP BY CAJA, Z, FECHA),0) 
		 + ISNULL((SELECT TOP 1 SUM(CASE TIPOMOV WHEN 4 THEN IMPORTE*-1 ELSE IMPORTE END) IMPORTE 
				FROM FONDOCAJA FC WHERE FC.CODCONCEPTOPAGO=-1 AND FC.TIPOMOV IN (4) AND FC.Z=ARQ.NUMERO AND FC.CAJA=ARQ.CAJA AND DZ.CODMEDIOPAGO= ''1''
			 GROUP BY CAJA, Z, FECHA),0) 
		FROM dbo.RIPV_DECLARADOZ DZ LEFT JOIN VENCIMFPAGO V ON DZ.CODMEDIOPAGO=V.CODTIPOPAGO 

		WHERE DZ.CAJA=ARQ.CAJA AND DZ.NUMZ=ARQ.NUMERO AND V.CODFORMAPAGO=FP.CODFORMAPAGO AND DZ.TIPO=0
		GROUP BY DZ.CODMEDIOPAGO),0) DECLARADO

	
	,  ISNULL((SELECT  ISNULL((SELECT TOP 1 SUM(CASE TIPOMOVCAJA WHEN 4 THEN IMPORTE*-1 ELSE IMPORTE END) IMPORTE 
				FROM PAGOS FC WHERE FC.CODCONCEPTOPAGO=-1 AND FC.TIPOMOVCAJA IN (1,2,3) AND FC.Z=ARQ.NUMERO AND FC.CAJA=ARQ.CAJA AND DZ.CODMEDIOPAGO= ''1''
			 GROUP BY CAJA, Z, FECHA),0) 
		 + ISNULL((SELECT TOP 1 SUM(CASE TIPOMOV WHEN 4 THEN IMPORTE*-1 ELSE IMPORTE END) IMPORTE 
				FROM FONDOCAJA FC WHERE FC.CODCONCEPTOPAGO=-1 AND FC.TIPOMOV IN (4) AND FC.Z=ARQ.NUMERO AND FC.CAJA=ARQ.CAJA AND DZ.CODMEDIOPAGO= ''1''
			 GROUP BY CAJA, Z, FECHA),0) 
		FROM dbo.RIPV_DECLARADOZ DZ WHERE DZ.CAJA=ARQ.CAJA AND DZ.NUMZ=ARQ.NUMERO AND DZ.CODMEDIOPAGO=FP.CODFORMAPAGO AND DZ.TIPO=0
		GROUP BY DZ.CODMEDIOPAGO),0) GASTOS
	, S.SERIE SERIECAJA
	, ARQ.FO
	, ARQ.CERRADO
	, FP.CODMONEDA
	, UPPER(ISNULL((SELECT DZ.OBSERVACIONES FROM dbo.RIPV_DECLARADOZ DZ WHERE DZ.CAJA=ARQ.CAJA AND DZ.NUMZ=ARQ.NUMERO AND DZ.CODMEDIOPAGO=FP.CODFORMAPAGO AND DZ.TIPO=0 AND DZ.IMPORTE <>0),'''')) OBSERVACION
FROM  
	FORMASPAGO FP WITH(NOLOCK)
	INNER JOIN MONEDAS M WITH(NOLOCK) ON FP.CODMONEDA=M.CODMONEDA 
	, (SELECT SERIE, DESCRIPCION FROM SERIES WITH(NOLOCK) WHERE SERIE LIKE @CAJA) S INNER JOIN  ARQUEOS ARQ ON S.SERIE=ARQ.CAJA 
	
WHERE
	S.SERIE LIKE @CAJA
	AND ARQ.FECHA=@FECHA AND ARQ.ARQUEO=''Z'' ) TABLA
WHERE IMPORTE<>0 OR DECLARADO<>0 OR CODFORMAPAGO=''1''
)
		')
	END

    `
  ]
};