export const QuerysConfiguracion = {
  getConfiguracion: [
    `
    IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'ripAppWeb')
    BEGIN
      EXEC('CREATE SCHEMA [ripAppWeb]')
    END
    `,
    `
    IF NOT EXISTS (SELECT * FROM sys.objects 
    WHERE object_id = OBJECT_ID(N'[ripAppWeb].[CONFIGURACIONCUENTAS]') 
    AND type in (N'U'))
    BEGIN
      CREATE TABLE [ripAppWeb].[CONFIGURACIONCUENTAS](
        [SOBRANTEVENTA] [nvarchar](20) NULL,
        [FALTANTEVENTA] [nvarchar](20) NULL,
        [SOBRANTEREDONDEO] [nvarchar](20) NULL,
        [FALTANTEREDONDEO] [nvarchar](20) NULL,
        [IVA] [nvarchar](20) NULL,
        [COMISIONBANCARIA] [nvarchar](20) NULL,
        [RAIZPAGARE] [nvarchar](20) NULL,
        [RAIZUTILIDAD] [nvarchar](20) NULL,
        [APERTURA] [nchar](10) NULL
      ) ON [PRIMARY]
    END
    `,
    `
    IF NOT EXISTS (SELECT * FROM sys.objects 
    WHERE object_id = OBJECT_ID(N'[ripAppWeb].[MODULOS]') 
    AND type in (N'U'))
    BEGIN
      CREATE TABLE [ripAppWeb].[MODULOS](
        [CODMODULO] [int] NOT NULL PRIMARY KEY,
        [DESCRIPCION] [NVARCHAR](50) NOT NULL,
        [VERSION] [NVARCHAR](15) NOT NULL,
        [FECHAVERSION] [DATETIME] NOT NULL default GETDATE(),
        [FECHAMODIFICADO] [DATETIME] NOT NULL default GETDATE()
      ) ON [PRIMARY]

      INSERT INTO [ripAppWeb].[MODULOS] (CODMODULO, DESCRIPCION, VERSION) VALUES (1, 'MOVIMIENTO DE INVENTARIO', '1.0.0')
      INSERT INTO [ripAppWeb].[MODULOS] (CODMODULO, DESCRIPCION, VERSION) VALUES (2, 'LIBRO DE VENTAS', '1.0.0')
      INSERT INTO [ripAppWeb].[MODULOS] (CODMODULO, DESCRIPCION, VERSION) VALUES (3, 'LIBRO DE COMPRAS', '1.0.0')
      INSERT INTO [ripAppWeb].[MODULOS] (CODMODULO, DESCRIPCION, VERSION) VALUES (4, 'RETENCIONES', '1.0.0')
      INSERT INTO [ripAppWeb].[MODULOS] (CODMODULO, DESCRIPCION, VERSION) VALUES (5, 'RESUMEN IGTF', '1.0.0')
      INSERT INTO [ripAppWeb].[MODULOS] (CODMODULO, DESCRIPCION, VERSION) VALUES (6, 'CIERRE DE CAJA', '1.0.0')
      INSERT INTO [ripAppWeb].[MODULOS] (CODMODULO, DESCRIPCION, VERSION) VALUES (9999, 'CONFIGURACION', '1.0.0')
    END

    `,
    `
    IF NOT EXISTS (SELECT * FROM sys.objects 
    WHERE object_id = OBJECT_ID(N'[ripAppWeb].[SUBMODULOS]') 
    AND type in (N'U'))
    BEGIN
      CREATE TABLE [ripAppWeb].[SUBMODULOS](
        [CODMODULO] [int] NOT NULL REFERENCES [ripAppWeb].[MODULOS](CODMODULO),
        [CODSUBMODULO] [int] NOT NULL,
        [DESCRIPCION] [NVARCHAR](50) NOT NULL,
        [VERSION] [NVARCHAR](15) NOT NULL,
        [FECHAVERSION] [DATETIME] NOT NULL default GETDATE(),
        [FECHAMODIFICADO] [DATETIME] NOT NULL default GETDATE(),
        CONSTRAINT PK_SUBMODULOS PRIMARY KEY (CODMODULO, CODSUBMODULO)
      ) ON [PRIMARY]
  
    INSERT INTO [ripAppWeb].[SUBMODULOS] (CODMODULO, CODSUBMODULO, DESCRIPCION, VERSION) VALUES (1, 1, 'MOV. INV. ESTANDAR', '1.0.0')
    INSERT INTO [ripAppWeb].[SUBMODULOS] (CODMODULO, CODSUBMODULO, DESCRIPCION, VERSION) VALUES (1, 2, 'MOV. INV. CENTRO COSTO', '1.0.0')
    INSERT INTO [ripAppWeb].[SUBMODULOS] (CODMODULO, CODSUBMODULO, DESCRIPCION, VERSION) VALUES (2, 1, 'LIBRO DE VENTA AGRUPADO', '1.0.0')
    INSERT INTO [ripAppWeb].[SUBMODULOS] (CODMODULO, CODSUBMODULO, DESCRIPCION, VERSION) VALUES (2, 2, 'LIBRO DE VENTA DETALLADO', '1.0.0')
    INSERT INTO [ripAppWeb].[SUBMODULOS] (CODMODULO, CODSUBMODULO, DESCRIPCION, VERSION) VALUES (2, 3, 'LIBRO DE VENTA ISLA', '1.0.0')
    INSERT INTO [ripAppWeb].[SUBMODULOS] (CODMODULO, CODSUBMODULO, DESCRIPCION, VERSION) VALUES (4, 1, 'RETENCIONES IVA', '1.0.0')
    INSERT INTO [ripAppWeb].[SUBMODULOS] (CODMODULO, CODSUBMODULO, DESCRIPCION, VERSION) VALUES (4, 2, 'RETENCIONES ISLR', '1.0.0')
    INSERT INTO [ripAppWeb].[SUBMODULOS] (CODMODULO, CODSUBMODULO, DESCRIPCION, VERSION) VALUES (6, 1, 'VER CAJAS', '1.0.0')
    INSERT INTO [ripAppWeb].[SUBMODULOS] (CODMODULO, CODSUBMODULO, DESCRIPCION, VERSION) VALUES (6, 2, 'CONTABILIZAR', '1.0.0')
    INSERT INTO [ripAppWeb].[SUBMODULOS] (CODMODULO, CODSUBMODULO, DESCRIPCION, VERSION) VALUES (6, 3, 'DESCONTABILIZAR', '1.0.0')  
    INSERT INTO [ripAppWeb].[SUBMODULOS] (CODMODULO, CODSUBMODULO, DESCRIPCION, VERSION) VALUES (6, 999, 'CONFIGURACION', '1.0.0')

    END   
    `,
    `
    IF NOT EXISTS (SELECT * FROM sys.objects 
    WHERE object_id = OBJECT_ID(N'[ripAppWeb].[PERMISOSMODULOS]') 
    AND type in (N'U'))
    BEGIN
      CREATE TABLE [ripAppWeb].[PERMISOSMODULOS](
        [CODUSUARIO] [int] NOT NULL,
        [CODMODULO] [int] NOT NULL REFERENCES [ripAppWeb].[MODULOS](CODMODULO),
        [ACTIVO] [CHAR](1) NOT NULL DEFAULT 'F',
        [OTORGABLE] [CHAR](1) NOT NULL DEFAULT 'F',
        [FECHAMODIFICADO] [DATETIME] NOT NULL DEFAULT GETDATE(),
        CONSTRAINT PK_PERMISOSMODULOS PRIMARY KEY (CODUSUARIO, CODMODULO)
      ) ON [PRIMARY]
  
   INSERT INTO [ripAppWeb].[PERMISOSMODULOS] (CODUSUARIO, CODMODULO, ACTIVO, OTORGABLE) VALUES (0, 1, 'T', 'T')
   INSERT INTO [ripAppWeb].[PERMISOSMODULOS] (CODUSUARIO, CODMODULO, ACTIVO, OTORGABLE) VALUES (0, 2, 'T', 'T')
   INSERT INTO [ripAppWeb].[PERMISOSMODULOS] (CODUSUARIO, CODMODULO, ACTIVO, OTORGABLE) VALUES (0, 3, 'T', 'T')
   INSERT INTO [ripAppWeb].[PERMISOSMODULOS] (CODUSUARIO, CODMODULO, ACTIVO, OTORGABLE) VALUES (0, 4, 'T', 'T')
   INSERT INTO [ripAppWeb].[PERMISOSMODULOS] (CODUSUARIO, CODMODULO, ACTIVO, OTORGABLE) VALUES (0, 5, 'T', 'T')
   INSERT INTO [ripAppWeb].[PERMISOSMODULOS] (CODUSUARIO, CODMODULO, ACTIVO, OTORGABLE) VALUES (0, 6, 'T', 'T')
   INSERT INTO [ripAppWeb].[PERMISOSMODULOS] (CODUSUARIO, CODMODULO, ACTIVO, OTORGABLE) VALUES (0, 9999, 'T', 'T') 
    END   
    `,
    `
    IF NOT EXISTS (SELECT * FROM sys.objects 
    WHERE object_id = OBJECT_ID(N'[ripAppWeb].[PERMISOSUBMODULOS]') 
    AND type in (N'U'))
    BEGIN
      CREATE TABLE [ripAppWeb].[PERMISOSUBMODULOS](
        [CODUSUARIO] [int] NOT NULL,
        [CODMODULO] [int] NOT NULL ,
        [CODSUBMODULO] [int] NOT NULL,
        [ACTIVO] [CHAR](1) NOT NULL DEFAULT 'F',
        [OTORGABLE] [CHAR](1) NOT NULL DEFAULT 'F',
        [FECHAMODIFICADO] [DATETIME] NOT NULL DEFAULT GETDATE(),
        FOREIGN KEY (CODMODULO) REFERENCES [ripAppWeb].[MODULOS](CODMODULO),
        FOREIGN KEY (CODMODULO, CODSUBMODULO) REFERENCES [ripAppWeb].[SUBMODULOS](CODMODULO, CODSUBMODULO),
        CONSTRAINT PK_PERMISOSUBMODULOS PRIMARY KEY (CODUSUARIO, CODMODULO, CODSUBMODULO)
      ) ON [PRIMARY]
  
   INSERT INTO [ripAppWeb].[PERMISOSUBMODULOS] (CODUSUARIO, CODMODULO,CODSUBMODULO, ACTIVO, OTORGABLE) VALUES (0, 1,1, 'T', 'T') 
   INSERT INTO [ripAppWeb].[PERMISOSUBMODULOS] (CODUSUARIO, CODMODULO,CODSUBMODULO, ACTIVO, OTORGABLE) VALUES (0, 1,2, 'T', 'T')
   INSERT INTO [ripAppWeb].[PERMISOSUBMODULOS] (CODUSUARIO, CODMODULO,CODSUBMODULO, ACTIVO, OTORGABLE) VALUES (0, 2,1, 'T', 'T')
   INSERT INTO [ripAppWeb].[PERMISOSUBMODULOS] (CODUSUARIO, CODMODULO,CODSUBMODULO, ACTIVO, OTORGABLE) VALUES (0, 2,2, 'T', 'T')
   INSERT INTO [ripAppWeb].[PERMISOSUBMODULOS] (CODUSUARIO, CODMODULO,CODSUBMODULO, ACTIVO, OTORGABLE) VALUES (0, 2,3, 'T', 'T')
   INSERT INTO [ripAppWeb].[PERMISOSUBMODULOS] (CODUSUARIO, CODMODULO,CODSUBMODULO, ACTIVO, OTORGABLE) VALUES (0, 4,1, 'T', 'T')
   INSERT INTO [ripAppWeb].[PERMISOSUBMODULOS] (CODUSUARIO, CODMODULO,CODSUBMODULO, ACTIVO, OTORGABLE) VALUES (0, 4,2, 'T', 'T')
   INSERT INTO [ripAppWeb].[PERMISOSUBMODULOS] (CODUSUARIO, CODMODULO,CODSUBMODULO, ACTIVO, OTORGABLE) VALUES (0, 6,1, 'T', 'T')
   INSERT INTO [ripAppWeb].[PERMISOSUBMODULOS] (CODUSUARIO, CODMODULO,CODSUBMODULO, ACTIVO, OTORGABLE) VALUES (0, 6,2, 'T', 'T')
   INSERT INTO [ripAppWeb].[PERMISOSUBMODULOS] (CODUSUARIO, CODMODULO,CODSUBMODULO, ACTIVO, OTORGABLE) VALUES (0, 6,3, 'T', 'T')  
   INSERT INTO [ripAppWeb].[PERMISOSUBMODULOS] (CODUSUARIO, CODMODULO,CODSUBMODULO, ACTIVO, OTORGABLE) VALUES (0, 6,999, 'T', 'T')

    END   
    `,`
	IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ripAppWeb].[PERMISOSUSUARIOS]') AND type in (N'V'))
	BEGIN
	EXEC ('
	CREATE VIEW [ripAppWeb].[PERMISOSUSUARIOS] AS
		SELECT
			US.CODUSUARIO,
			US.USUARIO,
			PM.CODMODULO,
			M.DESCRIPCION AS MODULO,
			PM.ACTIVO MODULOACTIVO,
			PM.OTORGABLE MODULOOTORGABLE,
			SPM.CODSUBMODULO,
			SM.DESCRIPCION AS SUBMODULO,
			ISNULL(SPM.ACTIVO,CASE WHEN PM.ACTIVO =''T'' THEN ''T'' ELSE ''F'' END) SUBMODULOACTIVO,
			ISNULL(SPM.OTORGABLE,''F'') SUBMODULOOTORGABLE
		
		FROM
			USUARIOS US WITH(NOLOCK)
			INNER JOIN ripAppWeb.PERMISOSMODULOS PM ON PM.CODUSUARIO = US.CODUSUARIO
			LEFT JOIN  ripAppWeb.PERMISOSUBMODULOS SPM ON SPM.CODUSUARIO =  PM.CODUSUARIO AND PM.CODMODULO= SPM.CODMODULO
			LEFT JOIN ripAppWeb.SUBMODULOS SM ON SM.CODSUBMODULO = SPM.CODSUBMODULO AND SM.CODMODULO = PM.CODMODULO
			INNER JOIN ripAppWeb.MODULOS M ON M.CODMODULO = PM.CODMODULO

	')
	END
	`,
	`
		IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ripAppWeb].[EMPRESAUSUARIOS]') AND type IN (N'V'))
		BEGIN
		EXEC ('
		CREATE VIEW [ripAppWeb].[EMPRESAUSUARIOS] AS 
		SELECT
			US.CODUSUARIO,
			US.USUARIO,
			EMP.CODEMPRESA CODEMPRESAGESTION,
			EMP.TITULO GESTION,
			SUBSTRING(EMP.PATHBD, CHARINDEX('':'', EMP.PATHBD) + 1, LEN(EMP.PATHBD)) BDGESTION,
			EMPC.CODIGO CODEMPRESACONTABLE,
			EMPC.DESCRIPCION CONTABLE,
			SUBSTRING(EMPC.PATHBD, CHARINDEX('':'', EMPC.PATHBD) + 1, LEN(EMPC.PATHBD)) BDCONTABLE,
			EMPC.EJERCICIO
		FROM 
			dbo.USUARIOS US WITH(NOLOCK)
			INNER JOIN dbo.EMPRESASUSUARIO EU  WITH(NOLOCK) ON EU.CODUSUARIO = US.CODUSUARIO
			INNER JOIN dbo.EMPRESAS EMP WITH(NOLOCK) ON EMP.CODEMPRESA = EU.CODEMPRESA
			LEFT JOIN dbo.EMPRESASCONTAUSUARIO ECU WITH(NOLOCK) ON ECU.CODUSUARIO = US.CODUSUARIO AND ECU.CODEMPGESTION =  EMP.CODEMPRESA
			LEFT JOIN dbo.EMPRESASCONTABLES EMPC WITH(NOLOCK) ON EMPC.CODIGO = ECU.CODEMPRESA
		')
		END 
	`
    
      ],
  getConfiguracionEmpresas:[
    `
    IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'ripAppWeb')
    BEGIN
      EXEC('CREATE SCHEMA [ripAppWeb]')
    END
    `,
    `
    IF NOT EXISTS (SELECT * FROM sys.objects
				WHERE object_id = OBJECT_ID(N'[ripAppWeb].[DECLARADOZ]') 
				AND type in (N'V'))
      BEGIN 
        EXEC ('
            CREATE VIEW [ripAppWeb].[DECLARADOZ] AS
              SELECT 
                DZ.TIPO
                , DZ.CAJA
                , DZ.NUMZ
                , DZ.CODMONEDA
                , ISNULL(COTI.COTIZACION,1)*IMPORTE IMPORTE
                , DZ.CODMEDIOPAGO
                , DZ.OBSERVACIONES
                , DZ.IDMOTIVO
                , DZ.AUTO
                , DZ.DESCUADRE

              FROM
                dbo.ARQUEOS ARQ  WITH (NOLOCK)
                INNER JOIN dbo.DECLARADOZ DZ  WITH (NOLOCK) ON DZ.CAJA=ARQ.CAJA AND DZ.NUMZ=ARQ.NUMERO AND ARQ.ARQUEO=''Z''
                LEFT JOIN dbo.COTIZACIONES COTI  WITH (NOLOCK) ON DZ.CODMONEDA=COTI.CODMONEDA AND ARQ.FECHA=COTI.FECHA
          ')
      END 

    `,
	`
		IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id =OBJECT_ID(N'[ripAppWeb].[TIENDASEMPRESA]') AND type IN (N'V'))
		BEGIN
			EXEC ('
				CREATE VIEW [ripAppWeb].[TIENDASEMPRESA] AS 
				SELECT  DISTINCT
					S.SERIE SERIE,
					S.DESCRIPCION DESCRIPCION,
					EC.BDCONTABLE
					, ISNULL(SCL.CODCLIENTE,0) CODCLIENTE
					, CAJA.IDFRONT
				FROM
					SERIES S 
					INNER JOIN GENERAL.ripAppWeb.EMPRESAUSUARIOS EC  ON EC.CODEMPRESACONTABLE=CAST(SUBSTRING(S.CONTABILIDADB,6,3) AS INT) AND EC.EJERCICIO=CAST(SUBSTRING(S.CONTABILIDADB,2,4) AS INT)
					LEFT JOIN dbo.SERIESCAMPOSLIBRES SCL ON S.SERIE=SCL.SERIE
					INNER JOIN (SELECT RC.IDFRONT, SUBSTRING(RC.SERIEINVENTARIO,1,2) COLLATE Latin1_General_CS_AI SERIE FROM dbo.  REM_CAJASFRONT RC WHERE CAJAFRONT=1
							UNION ALL 
							SELECT 1, SERIE FROM dbo.SERIES WHERE SERIE LIKE ''___''AND NOT SERIE LIKE ''%0%'') CAJA ON S.SERIE=CAJA.SERIE 
				WHERE
					(S.SERIE LIKE ''__'' OR S.SERIE LIKE ''___'')
					AND S.SERIE NOT LIKE ''Z%''
			')
		END
	`,
	
    `
    IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ripAppWeb].[FORMASPAGOS]') 
				AND type in (N'U')) 
      BEGIN
        CREATE TABLE [ripAppWeb].[FORMASPAGOS](
          [ID] [int] IDENTITY(1,1) NOT NULL,
          [DESCRIPCION] [nvarchar](100) NOT NULL
        ) ON [PRIMARY]
      END
      
    `, 
    `
    IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ripAppWeb].[RELACIONFORMASPAGO]') 
				AND type in (N'U')) 
      BEGIN
       CREATE TABLE [ripAppWeb].[RELACIONFORMASPAGO](
          [CODFORMAPAGO] [nvarchar](6) NULL,
          [IDFORMAPAGO] [int] NULL
        ) ON [PRIMARY]
      END
      
    `,
    `
    IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ripAppWeb].[PROC_GETCOTIZACION]') AND type in(N'P'))
	BEGIN
	  EXEC ('
        CREATE PROCEDURE [ripAppWeb].[PROC_GETCOTIZACION](@FECHA AS DATE , @IMPORTE AS FLOAT=1) AS SET NOCOUNT ON
            DECLARE 
              @MONEDA_VES AS INT =4
              , @MONEDA_USD AS INT=2
              , @MONEDA_EUR AS INT=3

            DECLARE
              @ISO_MONEDA_VES AS NVARCHAR(3)=(SELECT M.CODIGOISO FROM MONEDAS M WHERE M.CODMONEDA=@MONEDA_VES)
              , @ISO_MONEDA_USD AS NVARCHAR(3)=(SELECT M.CODIGOISO FROM MONEDAS M WHERE M.CODMONEDA=@MONEDA_USD)
              , @ISO_MONEDA_EUR AS NVARCHAR(3)=(SELECT M.CODIGOISO FROM MONEDAS M WHERE M.CODMONEDA=@MONEDA_EUR)

            --PRIMERO DE BS A TODAS LAS MONEDAS
            SELECT FORMAT(@IMPORTE,''n'',''es-VE'')+'' ''+ @ISO_MONEDA_VES+'' = ''+FORMAT(@IMPORTE/dbo.F_GET_COTIZACION(@FECHA, @MONEDA_VES),''n'',''es-VE'')+'' ''+@ISO_MONEDA_USD MENSAJE
            UNION ALL
            SELECT FORMAT(@IMPORTE,''n'',''es-VE'')+'' ''+ @ISO_MONEDA_VES+'' = ''+FORMAT(@IMPORTE/dbo.F_GET_COTIZACION(@FECHA, @MONEDA_VES)*1/dbo.F_GET_COTIZACION(@FECHA, @MONEDA_EUR),''n'',''es-VE'')+'' ''+@ISO_MONEDA_EUR MENSAJE
            --AHORA DE USD AL RESTO
            UNION ALL
            SELECT FORMAT(@IMPORTE,''n'',''es-VE'')+'' ''+ @ISO_MONEDA_USD+'' = ''+FORMAT(@IMPORTE*dbo.F_GET_COTIZACION(@FECHA, @MONEDA_VES),''n'',''es-VE'')+'' ''+@ISO_MONEDA_VES MENSAJE
            UNION ALL
            SELECT FORMAT(@IMPORTE,''n'',''es-VE'')+'' ''+ @ISO_MONEDA_USD+'' = ''+FORMAT(@IMPORTE*1/dbo.F_GET_COTIZACION(@FECHA, @MONEDA_EUR),''n'',''es-VE'')+'' ''+@ISO_MONEDA_EUR MENSAJE
            --AHORA DE EUROS AL RESTO
            --AHORA DE USD AL RESTO
            UNION ALL
            SELECT FORMAT(@IMPORTE,''n'',''es-VE'')+'' ''+ @ISO_MONEDA_EUR+'' = ''+FORMAT(@IMPORTE*dbo.F_GET_COTIZACION(@FECHA, @MONEDA_EUR)*dbo.F_GET_COTIZACION(@FECHA, @MONEDA_VES),''n'',''es-VE'')+'' ''+@ISO_MONEDA_VES MENSAJE
            UNION ALL
            SELECT FORMAT(@IMPORTE,''n'',''es-VE'')+'' ''+ @ISO_MONEDA_EUR+'' = ''+FORMAT(@IMPORTE*dbo.F_GET_COTIZACION(@FECHA, @MONEDA_EUR),''n'',''es-VE'')+'' ''+@ISO_MONEDA_USD MENSAJE
	')
	END

    `,
    `
    IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ripAppWeb].[DIFERENCIAFRONT_WEB]') AND type in(N'IF'))
	BEGIN
	EXEC ('
	CREATE FUNCTION [ripAppWeb].[DIFERENCIAFRONT_WEB](@FECHA AS DATETIME, @CAJA AS NVARCHAR(4) ) RETURNS TABLE
AS RETURN (
SELECT CAJA, FECHA,  Z, CODFORMAPAGO, DESCRIPCION,
	IMPORTE,  IMPORTE*dbo.F_GET_COTIZACION(@FECHA,4) IMPORTE_LOCAL, DECLARADO, DECLARADO*dbo.F_GET_COTIZACION(@FECHA,4) DECLARADO_LOCAL, 
		GASTOS, SERIECAJA, FO, CERRADO, ROUND(ROUND(CAST(IMPORTE AS FLOAT),2)-ROUND(CAST(DECLARADO AS FLOAT),2),2) DIFERENCIA, CODMONEDA, dbo.F_GET_COTIZACION(@FECHA,4) TASA_VES,OBSERVACION FROM (
SELECT  --FP.CODFORMAPAGO, FP.DESCRIPCION, S.SERIE SERIECAJA, S.DESCRIPCION CAJA, ARQ.NUMERO 
	ARQ.FECHA
	, S.DESCRIPCION CAJA
	, ARQ.NUMERO Z
	, FP.CODFORMAPAGO
	, FP.DESCRIPCION+'' (''+M.CODIGOISO+'')'' COLLATE Modern_Spanish_CI_AS DESCRIPCION
	, ISNULL((SELECT 
		SUM(T.IMPORTE*T.FACTORMONEDA)
		FROM
			dbo.FACTURASVENTA FV WITH(NOLOCK)
			INNER JOIN dbo.TESORERIA T WITH(NOLOCK) ON FV.NUMSERIE=T.SERIE AND FV.NUMFACTURA=T.NUMERO AND FV.N=T.N
		WHERE
			T.ORIGEN IN (''C'')
			AND T.TIPODOCUMENTO IN (''F'')
			AND T.SERIE LIKE ARQ.CAJA+''%''
			AND (FV.Z=ARQ.NUMERO)
			AND T.CODFORMAPAGO=FP.CODFORMAPAGO
			AND T.FECHADOCUMENTO=@FECHA
		GROUP BY 
			T.FECHADOCUMENTO, SUBSTRING(T.SERIE,1,3)),0) IMPORTE
	, ISNULL((SELECT SUM(DZ.IMPORTE*V.PORCENTAJE/100) 
		 + ISNULL((SELECT TOP 1 SUM(CASE TIPOMOVCAJA WHEN 4 THEN IMPORTE*-1 ELSE IMPORTE END) IMPORTE 
				FROM dbo.PAGOS FC WHERE FC.CODCONCEPTOPAGO=-1 AND FC.TIPOMOVCAJA IN (1,2,3) AND FC.Z=ARQ.NUMERO AND FC.CAJA=ARQ.CAJA AND DZ.CODMEDIOPAGO= ''1''
			 GROUP BY CAJA, Z, FECHA),0) 
		 + ISNULL((SELECT TOP 1 SUM(CASE TIPOMOV WHEN 4 THEN IMPORTE*-1 ELSE IMPORTE END) IMPORTE 
				FROM dbo.FONDOCAJA FC WHERE FC.CODCONCEPTOPAGO=-1 AND FC.TIPOMOV IN (4) AND FC.Z=ARQ.NUMERO AND FC.CAJA=ARQ.CAJA AND DZ.CODMEDIOPAGO= ''1''
			 GROUP BY CAJA, Z, FECHA),0) 
		FROM ripAppWeb.DECLARADOZ DZ LEFT JOIN VENCIMFPAGO V ON DZ.CODMEDIOPAGO=V.CODTIPOPAGO 

		WHERE DZ.CAJA=ARQ.CAJA AND DZ.NUMZ=ARQ.NUMERO AND V.CODFORMAPAGO=FP.CODFORMAPAGO AND DZ.TIPO=0
		GROUP BY DZ.CODMEDIOPAGO),0) DECLARADO
	,  ISNULL((SELECT  ISNULL((SELECT TOP 1 SUM(CASE TIPOMOVCAJA WHEN 4 THEN IMPORTE*-1 ELSE IMPORTE END) IMPORTE 
				FROM dbo.PAGOS FC WHERE FC.CODCONCEPTOPAGO=-1 AND FC.TIPOMOVCAJA IN (1,2,3) AND FC.Z=ARQ.NUMERO AND FC.CAJA=ARQ.CAJA AND DZ.CODMEDIOPAGO= ''1''
			 GROUP BY CAJA, Z, FECHA),0) 
		 + ISNULL((SELECT TOP 1 SUM(CASE TIPOMOV WHEN 4 THEN IMPORTE*-1 ELSE IMPORTE END) IMPORTE 
				FROM dbo.FONDOCAJA FC WHERE FC.CODCONCEPTOPAGO=-1 AND FC.TIPOMOV IN (4) AND FC.Z=ARQ.NUMERO AND FC.CAJA=ARQ.CAJA AND DZ.CODMEDIOPAGO= ''1''
			 GROUP BY CAJA, Z, FECHA),0) 
		FROM ripAppWeb.DECLARADOZ DZ WHERE DZ.CAJA=ARQ.CAJA AND DZ.NUMZ=ARQ.NUMERO AND DZ.CODMEDIOPAGO=FP.CODFORMAPAGO AND DZ.TIPO=0
		GROUP BY DZ.CODMEDIOPAGO),0) GASTOS
	, S.SERIE SERIECAJA
	, ARQ.FO
	, ARQ.CERRADO
	, FP.CODMONEDA
	, UPPER(ISNULL((SELECT DZ.OBSERVACIONES FROM ripAppWeb.DECLARADOZ DZ WHERE DZ.CAJA=ARQ.CAJA AND DZ.NUMZ=ARQ.NUMERO AND DZ.CODMEDIOPAGO=FP.CODFORMAPAGO AND DZ.TIPO=0 AND DZ.IMPORTE <>0),'''')) OBSERVACION
FROM  
	dbo.FORMASPAGO FP WITH(NOLOCK)
	INNER JOIN dbo.MONEDAS M WITH(NOLOCK) ON FP.CODMONEDA=M.CODMONEDA 
	, (SELECT SERIE, DESCRIPCION FROM dbo.SERIES WITH(NOLOCK) WHERE SERIE LIKE @CAJA) S INNER JOIN  dbo.ARQUEOS ARQ ON S.SERIE=ARQ.CAJA 
	
WHERE
	S.SERIE LIKE @CAJA
	AND ARQ.FECHA=@FECHA AND ARQ.ARQUEO=''Z'' ) TABLA
WHERE IMPORTE<>0 OR DECLARADO<>0 OR CODFORMAPAGO=''1''
)
		')
	END

    `,
    `
    IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ripAppWeb].[COBROS_FRONT]') AND type IN (N'TF'))
BEGIN 
EXEC ('CREATE FUNCTION [ripAppWeb].[COBROS_FRONT](@REDONDEO AS INT, @FECHA AS DATE, @CAJA AS NVARCHAR(4), @Z AS INT,
	@CUENTA_SOBRANTE_VENTA AS NVARCHAR(12), @CUENTA_FALTANTE_VENTA AS NVARCHAR(12))
	RETURNS 
		@RESULTADO 	TABLE (CAJA NVARCHAR(3) COLLATE Latin1_General_CS_AI, FECHA  DATE, Z  INT, CUENTA NVARCHAR(12) COLLATE Latin1_General_CS_AI, COMENTARIO NVARCHAR(255) COLLATE Latin1_General_CS_AI, DEBE FLOAT, HABER FLOAT, CENTROCOSTE NVARCHAR(6) COLLATE Latin1_General_CS_AI, CODMONEDA INT)
AS BEGIN

	DECLARE @DEVOLUCIONES AS FLOAT
	DECLARE @COD_FORMAPAGO_EFECTIVO AS NVARCHAR(3)
	DECLARE @CODMONEDA AS INT=(SELECT TOP 1 CODMONEDA FROM dbo.MONEDAS WHERE PRINCIPAL=''T'')
	SET @COD_FORMAPAGO_EFECTIVO=''-123''

	SET @DEVOLUCIONES = 0 --ISNULL((SELECT ISNULL(SUM(FV.TOTALNETO*FV.FACTORMONEDA),0) FROM dbo.FACTURASVENTA FV WHERE FV.FECHA=@FECHA AND FV.CAJA LIKE @CAJA AND FV.Z=@Z AND FV.TOTALNETO<0),0)
	--SELECT @DEVOLUCIONES

	INSERT INTO @RESULTADO 
	
	--ESTA PARTE DE LA CONSULTA ES SOLO PARA EL EFECTIVO, ASUMIENDO QUE LAS DEVOLUCIONES SIEMPRE SER?N EN EFECTIVO
	SELECT 
		DIF.SERIECAJA COLLATE Latin1_General_CS_AI CAJA,
		DIF.FECHA,
		DIF.Z,
		VFP.CUENTACOBRO COLLATE Latin1_General_CS_AI CUENTA,
		LTRIM(RTRIM(''CIERRE DE '' + UPPER(DIF.CAJA) + '' DEL '' + CONVERT(char(10), @FECHA, 103)+'' ''+ISNULL(DIF.OBSERVACION,'''') + '' '' +  ISNULL(RFP.DESCRIPCION,''***''))) COLLATE Latin1_General_CS_AI COMENTARIO,
		CASE
			WHEN ROUND(SUM(DIF.DECLARADO)-@DEVOLUCIONES, @REDONDEO)-@DEVOLUCIONES >= 0 THEN ROUND(SUM(DIF.DECLARADO * VFP.PORCENTAJE / 100)-@DEVOLUCIONES, @REDONDEO)
			ELSE 0.0
		END DEBE,
		CASE
			WHEN ROUND(SUM(DIF.DECLARADO), @REDONDEO)-@DEVOLUCIONES < 0 THEN ROUND(SUM(DIF.DECLARADO * -1 * VFP.PORCENTAJE / 100)-@DEVOLUCIONES, @REDONDEO)
			ELSE 0.0
		END HABER,
		SUBSTRING(@CAJA, 1, 2) COLLATE Latin1_General_CS_AI CENTROCOSTE,
		DIF.CODMONEDA
	FROM 
		ripAppWeb.DIFERENCIAFRONT_WEB(@FECHA, @CAJA)DIF
		INNER JOIN dbo.VENCIMFPAGO VFP ON DIF.CODFORMAPAGO = VFP.CODFORMAPAGO
		LEFT JOIN ripAppWeb.RELACIONFORMASPAGO RR ON DIF.CODFORMAPAGO = RR.CODFORMAPAGO collate Modern_Spanish_CI_AS
		LEFT JOIN ripAppWeb.FORMASPAGOS RFP  ON RR.IDFORMAPAGO = RFP.ID
	WHERE
		DIF.Z=@Z
		AND DIF.DECLARADO <> 0
		AND LEN(@CAJA) > 2
		AND DIF.CODFORMAPAGO=@COD_FORMAPAGO_EFECTIVO
	GROUP BY DIF.FECHA,
			 DIF.CAJA,
			 DIF.SERIECAJA,
			 VFP.CUENTACOBRO,
			 RR.IDFORMAPAGO,
			 DIF.Z, 
			 RFP.DESCRIPCION,
			 DIF.CODMONEDA,
			 ISNULL(DIF.OBSERVACION,'''') 
	UNION ALL
	--ESTA PARTE DE LA CONSULTA ES PARA TODO LO QUE NO SEA EFECTIVO
	SELECT 
		DIF.SERIECAJA COLLATE Latin1_General_CS_AI CAJA,
		DIF.FECHA,
		DIF.Z,
		VFP.CUENTACOBRO COLLATE Latin1_General_CS_AI CUENTA,
		LTRIM(RTRIM(''CIERRE DE '' + UPPER(DIF.CAJA) + '' DEL '' + CONVERT(char(10), @FECHA, 103) +'' ''+ISNULL(DIF.OBSERVACION,'''')  + '' '' +  ISNULL(RFP.DESCRIPCION,''***''))) COLLATE Latin1_General_CS_AI COMENTARIO,
		CASE
			WHEN ROUND(SUM(DIF.DECLARADO)-@DEVOLUCIONES, @REDONDEO) >= 0 THEN ROUND(SUM(DIF.DECLARADO * VFP.PORCENTAJE / 100), @REDONDEO)
			ELSE 0.0
		END DEBE,
		CASE
			WHEN ROUND(SUM(DIF.DECLARADO), @REDONDEO) < 0 THEN ROUND(SUM(DIF.DECLARADO * -1 * VFP.PORCENTAJE / 100), @REDONDEO)
			ELSE 0.0
		END HABER,
		SUBSTRING(@CAJA, 1, 2) COLLATE Latin1_General_CS_AI CENTROCOSTE,
		DIF.CODMONEDA
		
		
	FROM 
		ripAppWeb.DIFERENCIAFRONT_WEB(@FECHA, @CAJA)DIF
		INNER JOIN dbo.VENCIMFPAGO VFP ON DIF.CODFORMAPAGO = VFP.CODFORMAPAGO
		LEFT JOIN ripAppWeb.RELACIONFORMASPAGO RR ON DIF.CODFORMAPAGO = RR.CODFORMAPAGO collate Modern_Spanish_CI_AS
		LEFT JOIN ripAppWeb.FORMASPAGOS RFP  ON RR.IDFORMAPAGO = RFP.ID
	WHERE
		DIF.Z=@Z
		AND DIF.DECLARADO <> 0.0
		AND LEN(@CAJA) > 2
		AND DIF.CODFORMAPAGO<>@COD_FORMAPAGO_EFECTIVO
	GROUP BY DIF.FECHA,
			 DIF.CAJA,
			 DIF.SERIECAJA,
			 VFP.CUENTACOBRO,
			 RR.IDFORMAPAGO,
			 DIF.Z, 
			 RFP.DESCRIPCION,
			 DIF.CODMONEDA,
			 ISNULL(DIF.OBSERVACION,'''') 
	UNION ALL
	--ESTA PARTE DE LA CONSULTA ES PARA LAS DIFERENCIAS EN CIERRES
	SELECT 
		DIF.SERIECAJA CAJA
		, DIF.FECHA FECHA
		, DIF.Z
		, CASE 
			WHEN SUM(DIF.DIFERENCIA)>0 THEN @CUENTA_FALTANTE_VENTA
			ELSE @CUENTA_SOBRANTE_VENTA END CUENTA
		, ''CIERRE DE '' + UPPER(DIF.CAJA) + '' DEL '' + CONVERT(char(10), @FECHA, 103) COMENTARIO
		, CASE 
			WHEN SUM(DIF.DIFERENCIA)>0.0 THEN ROUND(SUM(DIF.DIFERENCIA),@REDONDEO) 
			ELSE 0.0 END DEBE
		, CASE 
			WHEN SUM(DIF.DIFERENCIA)<0.0 THEN ABS(ROUND(SUM(DIF.DIFERENCIA),@REDONDEO))
			ELSE 0.0  END HABER

		, SUBSTRING(@CAJA, 1, 2) CENTROCOSTE
		, @CODMONEDA CODMONEDA	
	FROM 
		ripAppWeb.DIFERENCIAFRONT_WEB(@FECHA, @CAJA) DIF 
	WHERE
		DIF.Z=@Z
	GROUP BY 
		DIF.FECHA,
		DIF.CAJA,
		DIF.SERIECAJA,
		DIF.Z

	RETURN
END
')
END


    `,
    `
    IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ripAppWeb].[COSTOVENTA]') AND type IN (N'TF'))
BEGIN
EXEC ('
CREATE FUNCTION [ripAppWeb].[COSTOVENTA] (@REDONDEO AS INT, @CAJA AS NVARCHAR(4), @Z AS INT )
RETURNS @TABLA TABLE
(
CAJA NVARCHAR(3) COLLATE Latin1_General_CS_AI,
FECHA DATE,
Z INT,
CUENTA NVARCHAR(12) COLLATE Latin1_General_CS_AI,
COMENTARIO NVARCHAR(100) COLLATE Latin1_General_CS_AI,
DEBE DECIMAL(18,2),
HABER DECIMAL(18,2),
CENTROCOSTE NVARCHAR(10) COLLATE Latin1_General_CS_AI
)
AS
BEGIN
--DECLARAR LAS VARIABLES AQUÍ
--DECLARE @CUENTA_COSTE AS NVARCHAR(9)=''51101001''
--, @CUENTA_DEVOL_COSTE AS NVARCHAR(9)=''51101001''
--, @CUENTA_COMPRA AS NVARCHAR(9)=''11401001''
--, @CUENTA_DEVOL_COMPRA AS NVARCHAR(9)=''11401001''
--, @TARIFA_COSTO AS INT=(SELECT PVPETIQUETAS FROM ALMACEN WHERE CODALMACEN=SUBSTRING(@CAJA,1,2)+''V'')

--INSERTAR LOS DATOS EN LA TABLA
		INSERT INTO @TABLA
		SELECT
			SUBSTRING(FV.NUMSERIE,1,3) COLLATE Latin1_General_CS_AI CAJA

			, MAX(FV.FECHA) FECHA
			, FV.Z
			, ART.CONTRAPARTIDACOSTEVENTAS CUENTA
			, ''CIERRE DE '' + UPPER(S.DESCRIPCION) + '' DEL '' + CONVERT(char(10), MAX(FV.FECHA), 103) + '' Z - '' + CONVERT(varchar, @Z) COLLATE Latin1_General_CS_AI COMENTARIO
			, ROUND(SUM(AVL.UNIDADESTOTAL*CASE WHEN ART.TIPOIMPUESTO = 0 THEN 0 ELSE (100*COSTEIVA)/(100+IMP.IVA) END), @REDONDEO) DEBE --esto puede que se tome de una tarifa
			, 0 HABER
			, ALM.CENTROCOSTE COLLATE Latin1_General_CS_AI CENTROCOSTE
		FROM
			dbo.FACTURASVENTA FV WITH(NOLOCK)
			INNER JOIN dbo.ALBVENTACAB AVC WITH(NOLOCK) ON FV.NUMSERIE=AVC.NUMSERIEFAC AND FV.NUMFACTURA=AVC.NUMFAC AND FV.N=AVC.NFAC
			INNER JOIN dbo.ALBVENTALIN AVL WITH(NOLOCK) ON AVC.NUMSERIE=AVL.NUMSERIE AND AVC.NUMALBARAN=AVL.NUMALBARAN AND AVC.N=AVL.N
			INNER JOIN dbo.ARTICULOS ART WITH(NOLOCK) ON ART.CODARTICULO = AVL.CODARTICULO
			LEFT JOIN  dbo.IMPUESTOS IMP WITH(NOLOCK) ON IMP.TIPOIVA = ART.TIPOIMPUESTO
			--LEFT JOIN  dbo.RIP_ULT_COSTO_USD(@FECHA) PV ON PV.CODARTICULO = AVL.CODARTICULO AND PV.TALLA = AVL.TALLA AND PV.COLOR =	AVL.TALLA AND PV.CODALMACEN = AVL.CODALMACEN
			--LEFT JOIN  dbo.COSTESPORALMACEN PV2 ON PV2.CODARTICULO = AVL.CODARTICULO AND PV2.TALLA = AVL.TALLA AND PV2.COLOR =	AVL.TALLA AND PV2.CODALMACEN = AVL.CODALMACEN
			--INNER JOIN dbo.PRECIOSVENTA PV WITH(NOLOCK) ON AVL.CODARTICULO=PV.CODARTICULO AND AVL.COLOR=PV.COLOR AND AVL.TALLA=PV.TALLA AND PV.IDTARIFAV=@TARIFA_COSTO
			INNER JOIN dbo.ALMACEN ALM WITH(NOLOCK) ON AVL.CODALMACEN=ALM.CODALMACEN
			INNER JOIN dbo.SERIES S WITH(NOLOCK) ON FV.CAJA=S.SERIE
		WHERE
			AVL.UNIDADESTOTAL>0	AND
			FV.CAJA LIKE @CAJA
			AND FV.Z=@Z
		GROUP BY
			SUBSTRING(FV.NUMSERIE,1,3)
			, FV.Z
			, ALM.CENTROCOSTE
			, S.DESCRIPCION
			,ART.CONTRAPARTIDACOSTEVENTAS
		UNION ALL
		--ESTO ES PARA LAS DEVOLUCIONES CONTRA COSTO
		SELECT
			SUBSTRING(FV.NUMSERIE,1,3) CAJA
			, MAX(FV.FECHA) FECHA
			, FV.Z
			, ART.CONTRAPARTIDADEVOLCOSTEVENTA
			, ''CIERRE DE '' + UPPER(S.DESCRIPCION) + '' DEL '' + CONVERT(char(10), MAX(FV.FECHA), 103) + '' Z - '' + CONVERT(varchar, @Z) COLLATE Latin1_General_CS_AI COMENTARIO
			, 0 DEBE
			, ROUND(SUM(CASE WHEN ART.TIPOIMPUESTO = 0 THEN 0 ELSE (100*COSTEIVA)/(100+IMP.IVA) END*ABS(AVL.UNIDADESTOTAL)), @REDONDEO)  HABER
			, ALM.CENTROCOSTE
		FROM
			dbo.FACTURASVENTA FV WITH(NOLOCK)
			INNER JOIN dbo.ALBVENTACAB AVC WITH(NOLOCK) ON FV.NUMSERIE=AVC.NUMSERIEFAC AND FV.NUMFACTURA=AVC.NUMFAC AND FV.N=AVC.NFAC
			INNER JOIN dbo.ALBVENTALIN AVL WITH(NOLOCK) ON AVC.NUMSERIE=AVL.NUMSERIE AND AVC.NUMALBARAN=AVL.NUMALBARAN AND AVC.N=AVL.N
			INNER JOIN dbo.ARTICULOS ART WITH(NOLOCK) ON ART.CODARTICULO = AVL.CODARTICULO
			LEFT JOIN  dbo.IMPUESTOS IMP WITH(NOLOCK) ON IMP.TIPOIVA = ART.TIPOIMPUESTO
			--LEFT JOIN  dbo.RIP_ULT_COSTO_USD(@FECHA) PV ON PV.CODARTICULO = AVL.CODARTICULO AND PV.TALLA = AVL.TALLA AND PV.COLOR =	AVL.TALLA AND PV.CODALMACEN = AVL.CODALMACEN
			--LEFT JOIN  dbo.COSTESPORALMACEN PV2 ON PV2.CODARTICULO = AVL.CODARTICULO AND PV2.TALLA = AVL.TALLA AND PV2.COLOR =	AVL.TALLA AND PV2.CODALMACEN = AVL.CODALMACEN
			INNER JOIN dbo.ALMACEN ALM WITH(NOLOCK) ON AVL.CODALMACEN=ALM.CODALMACEN
			INNER JOIN dbo.SERIES S WITH(NOLOCK) ON FV.CAJA=S.SERIE
		WHERE
			AVL.UNIDADESTOTAL<0
			AND FV.CAJA LIKE @CAJA
			AND FV.Z=@Z
		GROUP BY
			SUBSTRING(FV.NUMSERIE,1,3)
			, FV.Z
			, ALM.CENTROCOSTE
			, S.DESCRIPCION
			,ART.CONTRAPARTIDADEVOLCOSTEVENTA
		UNION ALL	
		--ESTO ES PARA LAS VENTAS
		SELECT
			SUBSTRING(FV.NUMSERIE,1,3) COLLATE Latin1_General_CS_AI CAJA

			, MAX(FV.FECHA) FECHA
			, FV.Z
			, ART.CONTRAPARTIDACOMPRA
			, ''CIERRE DE '' + UPPER(S.DESCRIPCION) + '' DEL '' + CONVERT(char(10), MAX(FV.FECHA), 103) + '' Z - '' + CONVERT(varchar, @Z) COLLATE Latin1_General_CS_AI COMENTARIO
			, 0 DEBE
			, ROUND(SUM(CASE WHEN ART.TIPOIMPUESTO = 0 THEN 0 ELSE (100*COSTEIVA)/(100+IMP.IVA) END*AVL.UNIDADESTOTAL), @REDONDEO) HABER --esto puede que se tome de una tarifa
			, ALM.CENTROCOSTE COLLATE Latin1_General_CS_AI CENTROCOSTE
		FROM
			dbo.FACTURASVENTA FV WITH(NOLOCK)
			INNER JOIN dbo.ALBVENTACAB AVC WITH(NOLOCK) ON FV.NUMSERIE=AVC.NUMSERIEFAC AND FV.NUMFACTURA=AVC.NUMFAC AND FV.N=AVC.NFAC
			INNER JOIN dbo.ALBVENTALIN AVL WITH(NOLOCK) ON AVC.NUMSERIE=AVL.NUMSERIE AND AVC.NUMALBARAN=AVL.NUMALBARAN AND AVC.N=AVL.N
			INNER JOIN dbo.ARTICULOS ART WITH(NOLOCK) ON ART.CODARTICULO = AVL.CODARTICULO
			LEFT JOIN  dbo.IMPUESTOS IMP WITH(NOLOCK) ON IMP.TIPOIVA = ART.TIPOIMPUESTO
			--LEFT JOIN  dbo.RIP_ULT_COSTO_USD(@FECHA) PV ON PV.CODARTICULO = AVL.CODARTICULO AND PV.TALLA = AVL.TALLA AND PV.COLOR =	AVL.TALLA AND PV.CODALMACEN = AVL.CODALMACEN
			--LEFT JOIN  dbo.COSTESPORALMACEN PV2 ON PV2.CODARTICULO = AVL.CODARTICULO AND PV2.TALLA = AVL.TALLA AND PV2.COLOR =	AVL.TALLA AND PV2.CODALMACEN = AVL.CODALMACEN
			INNER JOIN dbo.ALMACEN ALM WITH(NOLOCK) ON AVL.CODALMACEN=ALM.CODALMACEN
			INNER JOIN dbo.SERIES S WITH(NOLOCK) ON FV.CAJA=S.SERIE
		WHERE
			AVL.UNIDADESTOTAL>0	AND
			FV.CAJA LIKE @CAJA
			AND FV.Z=@Z
		GROUP BY
			SUBSTRING(FV.NUMSERIE,1,3)
			, FV.Z
			, ALM.CENTROCOSTE
			, S.DESCRIPCION
			,ART.CONTRAPARTIDACOMPRA
		UNION ALL
		--ESTO ES PARA LAS DEVOLUCIONES
		SELECT
			SUBSTRING(FV.NUMSERIE,1,3) CAJA
			, MAX(FV.FECHA) FECHA
			, FV.Z
			, ART.CONTRAPARTIDADEVOLCOMPRA
			, ''CIERRE DE '' + UPPER(S.DESCRIPCION) + '' DEL '' + CONVERT(char(10), MAX(FV.FECHA), 103) + '' Z - '' + CONVERT(varchar, @Z) COLLATE Latin1_General_CS_AI COMENTARIO
			, ROUND(SUM(CASE WHEN ART.TIPOIMPUESTO = 0 THEN 0 ELSE (100*COSTEIVA)/(100+IMP.IVA) END*ABS(AVL.UNIDADESTOTAL)), @REDONDEO) DEBE
			, 0 HABER
			, ALM.CENTROCOSTE
		FROM
			dbo.FACTURASVENTA FV WITH(NOLOCK)
			INNER JOIN dbo.ALBVENTACAB AVC WITH(NOLOCK) ON FV.NUMSERIE=AVC.NUMSERIEFAC AND FV.NUMFACTURA=AVC.NUMFAC AND FV.N=AVC.NFAC
			INNER JOIN dbo.ALBVENTALIN AVL WITH(NOLOCK) ON AVC.NUMSERIE=AVL.NUMSERIE AND AVC.NUMALBARAN=AVL.NUMALBARAN AND AVC.N=AVL.N
			INNER JOIN dbo.ARTICULOS ART WITH(NOLOCK) ON ART.CODARTICULO = AVL.CODARTICULO
			LEFT JOIN  dbo.IMPUESTOS IMP WITH(NOLOCK) ON IMP.TIPOIVA = ART.TIPOIMPUESTO
			--LEFT JOIN  dbo.RIP_ULT_COSTO_USD(@FECHA) PV ON PV.CODARTICULO = AVL.CODARTICULO AND PV.TALLA = AVL.TALLA AND PV.COLOR =	AVL.TALLA AND PV.CODALMACEN = AVL.CODALMACEN
			--LEFT JOIN  dbo.COSTESPORALMACEN PV2 ON PV2.CODARTICULO = AVL.CODARTICULO AND PV2.TALLA = AVL.TALLA AND PV2.COLOR =	AVL.TALLA AND PV2.CODALMACEN = AVL.CODALMACEN
			INNER JOIN dbo.ALMACEN ALM WITH(NOLOCK) ON AVL.CODALMACEN=ALM.CODALMACEN
			INNER JOIN dbo.SERIES S WITH(NOLOCK) ON FV.CAJA=S.SERIE
		WHERE
			AVL.UNIDADESTOTAL<0
			AND FV.CAJA LIKE @CAJA
			AND FV.Z=@Z
		GROUP BY
			 SUBSTRING(FV.NUMSERIE,1,3)
			, FV.Z
			, ALM.CENTROCOSTE
			, S.DESCRIPCION
			,ART.CONTRAPARTIDADEVOLCOMPRA

RETURN
END

')
END
    `,
    `IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ripAppWeb].[DIFERENCIAFRONT]') AND type IN (N'IF'))
BEGIN
EXEC ('
CREATE FUNCTION [ripAppWeb].[DIFERENCIAFRONT](@FECHA AS DATETIME, @CAJA AS NVARCHAR(4) ) RETURNS TABLE
AS RETURN (
SELECT @FECHA FECHA, *, ROUND(IMPORTE,2)-ROUND(DECLARADO,2) DIFERENCIA FROM (
SELECT 
	ISNULL(FP.CAJA,(SELECT DESCRIPCION FROM SERIES WHERE SERIE=ISNULL(MAX(T.CAJASALDADO),MAX(DECLARADO.CAJA))) ) CAJA
	, ISNULL(FP.CODFORMAPAGO,-1)  CODFORMAPAGO
	, ISNULL(FP.DESCRIPCION, ''BONO EMPLEADO'')  DESCRIPCION
	, ISNULL(MAX(T.IMPORTE),0) IMPORTE 
	, ISNULL(MAX(DECLARADO.IMPORTE),0) DECLARADO
	, FP.SERIECAJA
FROM 
	(SELECT FP.CODFORMAPAGO, FP.DESCRIPCION, S.SERIE SERIECAJA, S.DESCRIPCION CAJA FROM  dbo.FORMASPAGO FP, SERIES S WHERE
SERIE
LIKE ''___'' AND SERIE LIKE @CAJA ) FP
	FULL JOIN (
		SELECT
			T.FECHADOCUMENTO
			, SUBSTRING(T.SERIE,1,3) CAJASALDADO
			,T.CODFORMAPAGO
			,SUM(T.IMPORTE*T.FACTORMONEDA)  IMPORTE
		FROM
			dbo.TESORERIA T 
		WHERE
			T.FECHADOCUMENTO=@FECHA
			AND (T.SERIE LIKE ''___T'' OR T.SERIE LIKE ''___N'' OR T.SERIE LIKE ''___M'' OR T.SERIE LIKE ''___O'')
			AND T.SERIE LIKE @CAJA
		GROUP BY 
			T.FECHADOCUMENTO,
			SUBSTRING(T.SERIE,1,3),
			T.CODFORMAPAGO

	) T ON T.CODFORMAPAGO=FP.CODFORMAPAGO AND T.CAJASALDADO=FP.SERIECAJA
	FULL JOIN (
		SELECT
			A.FECHA
			,A.CAJA
			,ISNULL(V.CODFORMAPAGO,-1) CODFORMAPAGO
			,SUM(DZ.IMPORTE*V.PORCENTAJE/100) + ISNULL((SELECT TOP 1 SUM(CASE TIPOMOVCAJA WHEN 4 THEN IMPORTE*-1 ELSE IMPORTE END) 
IMPORTE 
		FROM PAGOS FC WHERE FC.CODCONCEPTOPAGO=-1 AND FC.TIPOMOVCAJA IN (0,1, 2,3) AND FC.Z=A.NUMERO AND FC.CAJA=A.CAJA AND V.CODFORMAPAGO=''1''
					GROUP BY CAJA, Z, FECHA),0) 
		+ ISNULL((SELECT TOP 1 SUM(CASE TIPOMOV WHEN 4 THEN IMPORTE*-1 ELSE IMPORTE END) 
IMPORTE 
		FROM dbo.FONDOCAJA FC WHERE FC.CODCONCEPTOPAGO=-1 AND FC.TIPOMOV IN (4) AND FC.Z=A.NUMERO AND FC.CAJA=A.CAJA AND V.CODFORMAPAGO=''1''
					GROUP BY CAJA, Z, FECHA),0)	IMPORTE
		FROM
			dbo.ARQUEOS A 
			INNER JOIN ripAppWeb.DECLARADOZ DZ ON A.CAJA=DZ.CAJA AND A.NUMERO=DZ.NUMZ AND A.ARQUEO=''Z'' AND DZ.TIPO=0
			LEFT JOIN dbo.VENCIMFPAGO V ON DZ.CODMEDIOPAGO=V.CODTIPOPAGO
		WHERE 
			A.FECHA=@FECHA AND A.CAJA LIKE @CAJA
		GROUP BY 
			A.FECHA,
			A.CAJA,
			V.CODFORMAPAGO,
			A.NUMERO) DECLARADO ON FP.CODFORMAPAGO=DECLARADO.CODFORMAPAGO AND FP.SERIECAJA=DECLARADO.CAJA
GROUP BY 
	FP.CODFORMAPAGO
	, FP.DESCRIPCION
	, FP.DESCRIPCION
	, FP.CAJA
	, FP.SERIECAJA
	) TABLA
WHERE ISNULL(IMPORTE,0)<>0 OR ISNULL(DECLARADO,0)<>0)

')
END
    `,
	`
	IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ripAppWeb].[DIFERENCIAS_FRONT]') AND type IN (N'IF'))
BEGIN
EXEC ('

CREATE FUNCTION [ripAppWeb].[DIFERENCIAS_FRONT](@REDONDEO AS INT, @FECHA AS DATE, @CAJA AS NVARCHAR(4), @Z AS INT,
	@CUENTA_SOBRANTE_REDONDEO AS NVARCHAR(12), @CUENTA_FALTANTE_REDONDEO AS NVARCHAR(12), @SOBRANTE_REDONDEO AS FLOAT)RETURNS TABLE
AS RETURN (
SELECT 
	SUBSTRING(@CAJA, 1,3) COLLATE Latin1_General_CS_AI CAJA
	, @FECHA FECHA
	, @Z Z
	, CASE 
		WHEN @SOBRANTE_REDONDEO>0 THEN @CUENTA_FALTANTE_REDONDEO
		ELSE @CUENTA_SOBRANTE_REDONDEO END COLLATE Latin1_General_CS_AI CUENTA
	, ''CIERRE DE '' + UPPER((SELECT DESCRIPCION FROM dbo.SERIES WHERE SERIE=SUBSTRING(@CAJA, 1,3))) + '' DEL '' + CONVERT(char(10), @FECHA, 103) + '' Z - '' + CONVERT(varchar, @Z) COMENTARIO
	, CASE 
		WHEN @SOBRANTE_REDONDEO<=0 THEN ABS(@SOBRANTE_REDONDEO)
		ELSE 0 END DEBE
    , CASE 
		WHEN @SOBRANTE_REDONDEO>0 THEN ABS(@SOBRANTE_REDONDEO)
		ELSE 0  END HABER

	, SUBSTRING(@CAJA, 1, 2) COLLATE Latin1_General_CS_AI CENTROCOSTE
 )


')
END
	`,
	`
	IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ripAppWeb].[IMPUESTOSFRONT]') AND type IN (N'TF'))
	BEGIN
	EXEC ('
	CREATE FUNCTION [ripAppWeb].[IMPUESTOSFRONT](@REDONDEO AS INT, @FECHA AS DATE , @CAJA AS NVARCHAR(4), @Z AS INT)
	RETURNS 
			@RESULTADO 	TABLE (CAJA NVARCHAR(3) COLLATE Latin1_General_CS_AI, FECHA  DATE, Z  INT, CUENTA NVARCHAR(12) COLLATE Latin1_General_CS_AI, COMENTARIO NVARCHAR(255) COLLATE Latin1_General_CS_AI, DEBE FLOAT, HABER FLOAT, CENTROCOSTE NVARCHAR(6) COLLATE Latin1_General_CS_AI)
	AS BEGIN
	DECLARE @COD_IGTF AS INT =3

	--PARA LAS FACTURAS

	INSERT INTO @RESULTADO 
	SELECT
		SUBSTRING(AVC.NUMSERIE, 1, 3) COLLATE Latin1_General_CS_AI CAJA,
		MAX(AVC.FECHA)FECHA,
		AVC.Z,
		IMP.CUENTAIVAREP COLLATE Latin1_General_CS_AI CUENTA,
		''CIERRE DE '' + UPPER(S.DESCRIPCION) + '' DEL '' + CONVERT(char(10), @FECHA, 103) + '' Z - '' + CONVERT(varchar, @Z) COLLATE Latin1_General_CS_AI COMENTARIO,
		CASE
			WHEN ROUND(SUM(AVL.TOTAL * AVC.FACTORMONEDA * (100-AVC.DTOCOMERCIAL)/100  * AVL.IVA/100),@REDONDEO) < 0 
			THEN ROUND(SUM(AVL.TOTAL * AVC.FACTORMONEDA * (100-AVC.DTOCOMERCIAL)/100  * AVL.IVA/100),@REDONDEO) * -1
			ELSE 0
		END DEBE,
		CASE
			WHEN ROUND(SUM(AVL.TOTAL * AVC.FACTORMONEDA * (100-AVC.DTOCOMERCIAL)/100  * AVL.IVA/100),@REDONDEO) >= 0 
			THEN ROUND(SUM(AVL.TOTAL * AVC.FACTORMONEDA * (100-AVC.DTOCOMERCIAL)/100  * AVL.IVA/100),@REDONDEO)
			ELSE 0
		END HABER
		, ALM.CENTROCOSTE COLLATE Latin1_General_CS_AI CENTROCOSTE
	FROM 
		dbo.ALBVENTACAB AVC WITH(NOLOCK)
		INNER JOIN dbo.ALBVENTALIN AVL WITH(NOLOCK) ON AVC.NUMSERIE = AVL.NUMSERIE AND AVC.NUMALBARAN = AVL.NUMALBARAN AND AVC.N = AVL.N
		INNER JOIN dbo.IMPUESTOS IMP WITH(NOLOCK) ON AVL.TIPOIMPUESTO = IMP.TIPOIVA
		INNER JOIN dbo.SERIES S WITH(NOLOCK) ON SUBSTRING(AVC.NUMSERIE, 1, 3) = S.SERIE
		INNER JOIN dbo.ALMACEN ALM WITH(NOLOCK) ON AVL.CODALMACEN=ALM.CODALMACEN
	WHERE 
		AVC.NUMSERIE LIKE @CAJA
		AND AVC.Z = @Z
		AND LEN(@CAJA) > 2
		AND AVC.FECHA = @FECHA
		AND AVC.TOTALNETO>0
		AND AVL.IVA<>0
	GROUP BY 
		IMP.CUENTAIVAREP,
		S.DESCRIPCION,
		AVC.Z,
		AVL.IVA,
		SUBSTRING(AVC.NUMSERIE, 1, 3),
		SUBSTRING(AVC.NUMSERIE, 3, 1),
		ALM.CENTROCOSTE
	UNION ALL
	--PARA LAS NOTAS DE CRÉDITOS
	SELECT
		SUBSTRING(AVC.NUMSERIE, 1, 3) COLLATE Latin1_General_CS_AI CAJA,
		MAX(AVC.FECHA)FECHA,
		AVC.Z,
		IMP.CUENTAIVAREP COLLATE Latin1_General_CS_AI CUENTA,
		''CIERRE DE '' + UPPER(S.DESCRIPCION) + '' DEL '' + CONVERT(char(10), @FECHA, 103) + ''Z - '' + CONVERT(varchar, @Z)  COLLATE Latin1_General_CS_AI COMENTARIO,
		CASE
			WHEN ROUND(SUM(AVL.TOTAL * AVC.FACTORMONEDA * (100-AVC.DTOCOMERCIAL)/100  * AVL.IVA/100),@REDONDEO) < 0 
			THEN ROUND(SUM(AVL.TOTAL * AVC.FACTORMONEDA * (100-AVC.DTOCOMERCIAL)/100  * AVL.IVA/100),@REDONDEO) * -1
			ELSE 0
		END DEBE,
		CASE
			WHEN ROUND(SUM(AVL.TOTAL * AVC.FACTORMONEDA * (100-AVC.DTOCOMERCIAL)/100  * AVL.IVA/100),@REDONDEO) >= 0 
			THEN ROUND(SUM(AVL.TOTAL * AVC.FACTORMONEDA * (100-AVC.DTOCOMERCIAL)/100  * AVL.IVA/100),@REDONDEO) 
			ELSE 0
		END HABER
		, ALM.CENTROCOSTE COLLATE Latin1_General_CS_AI CENTROCOSTE
	FROM 
		dbo.ALBVENTACAB AVC WITH(NOLOCK)
		INNER JOIN dbo.ALBVENTALIN AVL WITH(NOLOCK) ON AVC.NUMSERIE = AVL.NUMSERIE AND AVC.NUMALBARAN = AVL.NUMALBARAN AND AVC.N = AVL.N
		INNER JOIN dbo.IMPUESTOS IMP WITH(NOLOCK) ON AVL.TIPOIMPUESTO = IMP.TIPOIVA
		INNER JOIN dbo.SERIES S WITH(NOLOCK)  ON SUBSTRING(AVC.NUMSERIE, 1, 3) = S.SERIE
		INNER JOIN dbo.ALMACEN ALM WITH(NOLOCK) ON AVL.CODALMACEN=ALM.CODALMACEN
	WHERE 
		AVC.NUMSERIE LIKE @CAJA
		AND AVC.Z = @Z
		AND LEN(@CAJA) > 2
		AND AVC.FECHA = @FECHA
		AND AVC.TOTALNETO<0
		AND AVL.IVA<>0
	GROUP BY 
		IMP.CUENTAIVAREP,
		S.DESCRIPCION,
		AVC.Z,
		AVL.IVA,
		SUBSTRING(AVC.NUMSERIE, 1, 3),
		SUBSTRING(AVC.NUMSERIE, 3, 1),
		ALM.CENTROCOSTE
	UNION ALL
	--PARA EL IGTF
	SELECT
		SUBSTRING(FV.NUMSERIE, 1, 3) COLLATE Latin1_General_CS_AI CAJA,
		MAX(FV.FECHA)FECHA,
		FV.Z,
		CD.SUBCUENTAVENTAS COLLATE Latin1_General_CS_AI CUENTA,
		''CIERRE DE '' + UPPER(S.DESCRIPCION) + '' DEL '' + CONVERT(char(10), @FECHA, 103) + '' Z - '' + CONVERT(varchar, @Z) COLLATE Latin1_General_CS_AI COMENTARIO,
		CASE
			WHEN FLOOR((SUM(FVD.IMPORTE*FV.FACTORMONEDA)) * 100) / 100 < 0 
			THEN FLOOR((SUM(FVD.IMPORTE*FV.FACTORMONEDA)) * 100) / 100 * -1
			ELSE 0
		END DEBE,
		CASE
			WHEN FLOOR((SUM(FVD.IMPORTE*FV.FACTORMONEDA)) * 100) / 100 >= 0 
			THEN FLOOR((SUM(FVD.IMPORTE*FV.FACTORMONEDA)) * 100) / 100
			ELSE 0
		END HABER
		, SUBSTRING(FV.NUMSERIE,1,2) COLLATE Latin1_General_CS_AI CENTROCOSTE
	FROM
		dbo.FACTURASVENTA FV WITH(NOLOCK)
		INNER JOIN dbo.FACTURASVENTADTOS FVD WITH(NOLOCK) ON FV.NUMSERIE=FVD.NUMSERIE AND FV.NUMFACTURA=FVD.NUMERO AND FV.N=FVD.N
		INNER JOIN dbo.CARGOSDTOS CD WITH(NOLOCK)  ON FVD.CODDTO=CD.CODIGO
		INNER JOIN dbo.SERIES S WITH(NOLOCK)  ON SUBSTRING(FV.NUMSERIE, 1, 3) = S.SERIE
	WHERE
		FV.NUMSERIE LIKE @CAJA
		AND FV.Z = @Z
		AND LEN(@CAJA) > 2
		AND FV.FECHA = @FECHA
		AND FVD.CODDTO=@COD_IGTF

	GROUP BY 
		CD.SUBCUENTAVENTAS,
		S.DESCRIPCION,
		FV.Z,
		SUBSTRING(FV.NUMSERIE, 1, 2),
		SUBSTRING(FV.NUMSERIE, 1, 3),
		SUBSTRING(FV.NUMSERIE, 3, 1)

		RETURN
	END

	')
	END
	`,
	`IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ripAppWeb].[VENTAS]') AND type IN (N'IF'))
	BEGIN 
	EXEC('
	CREATE FUNCTION [ripAppWeb].[VENTAS](@REDONDEO AS INT, @CAJA AS NVARCHAR(4), @Z AS INT )RETURNS TABLE
	AS RETURN (
	SELECT
		SUBSTRING(FV.NUMSERIE,1,3) COLLATE Latin1_General_CS_AI CAJA  
		, MAX(FV.FECHA) FECHA
		, FV.Z
		, ISNULL(ART.CONTRAPARTIDAVENTA,''41101001'')  COLLATE Latin1_General_CS_AI CUENTA
		, ''CIERRE DE '' + UPPER(S.DESCRIPCION) + '' DEL '' + CONVERT(char(10), MAX(FV.FECHA), 103) + '' Z - '' + CONVERT(varchar, @Z) COLLATE Latin1_General_CS_AI COMENTARIO 
		, 0 DEBE
		, ROUND(SUM((AVL.TOTAL*FV.FACTORMONEDA) -(AVL.TOTAL*FV.FACTORMONEDA* AVC.DTOCOMERCIAL / 100)), @REDONDEO) HABER
		, ALM.CENTROCOSTE COLLATE Latin1_General_CS_AI CENTROCOSTE
	FROM
		dbo.FACTURASVENTA FV WITH(NOLOCK)
		INNER JOIN dbo.ALBVENTACAB AVC WITH(NOLOCK) ON FV.NUMSERIE=AVC.NUMSERIEFAC AND FV.NUMFACTURA=AVC.NUMFAC AND FV.N=AVC.NFAC
		INNER JOIN dbo.ALBVENTALIN AVL WITH(NOLOCK) ON AVC.NUMSERIE=AVL.NUMSERIE AND AVC.NUMALBARAN=AVL.NUMALBARAN AND AVC.N=AVL.N
		INNER JOIN dbo.ARTICULOS ART WITH(NOLOCK) ON AVL.CODARTICULO=ART.CODARTICULO
		INNER JOIN dbo.ALMACEN ALM WITH(NOLOCK) ON AVL.CODALMACEN=ALM.CODALMACEN
		INNER JOIN dbo.SERIES S WITH(NOLOCK) ON FV.CAJA=S.SERIE
	WHERE
		AVL.UNIDADESTOTAL>0	AND 
		FV.CAJA LIKE @CAJA
		AND FV.Z=@Z
	GROUP BY
		ISNULL(ART.CONTRAPARTIDAVENTA,''41101001'')
		, SUBSTRING(FV.NUMSERIE,1,3)  
		, FV.Z
		, ALM.CENTROCOSTE
		, S.DESCRIPCION
	UNION ALL 
	--ESTO ES PARA LAS DEVOLUCIONES
	SELECT
		SUBSTRING(FV.NUMSERIE,1,3) CAJA
		, MAX(FV.FECHA) FECHA
		, FV.Z
		, ISNULL(ART.CONTRAPARTIDADEVOLVENTA,''41102001'') 
		, ''CIERRE DE '' + UPPER(S.DESCRIPCION) + '' DEL '' + CONVERT(char(10), MAX(FV.FECHA), 103) COMENTARIO
		, ABS(ROUND(SUM((AVL.TOTAL*FV.FACTORMONEDA) - (AVL.TOTAL*FV.FACTORMONEDA* AVC.DTOCOMERCIAL / 100)), @REDONDEO)) DEBE
		, 0 HABER
		, ALM.CENTROCOSTE
	FROM
		dbo.FACTURASVENTA FV WITH(NOLOCK)
		INNER JOIN dbo.ALBVENTACAB AVC WITH(NOLOCK) ON FV.NUMSERIE=AVC.NUMSERIEFAC AND FV.NUMFACTURA=AVC.NUMFAC AND FV.N=AVC.NFAC
		INNER JOIN dbo.ALBVENTALIN AVL WITH(NOLOCK) ON AVC.NUMSERIE=AVL.NUMSERIE AND AVC.NUMALBARAN=AVL.NUMALBARAN AND AVC.N=AVL.N
		INNER JOIN dbo.ARTICULOS ART WITH(NOLOCK) ON AVL.CODARTICULO=ART.CODARTICULO
		INNER JOIN dbo.ALMACEN ALM WITH(NOLOCK) ON AVL.CODALMACEN=ALM.CODALMACEN
		INNER JOIN dbo.SERIES S WITH(NOLOCK) ON FV.CAJA=S.SERIE
	WHERE
		AVL.UNIDADESTOTAL<0 AND 
		FV.CAJA LIKE @CAJA
		AND FV.Z=@Z
	GROUP BY
		ISNULL(ART.CONTRAPARTIDADEVOLVENTA,''41102001'') 
		, SUBSTRING(FV.NUMSERIE,1,3) 
		, FV.Z
		, ALM.CENTROCOSTE
		, S.DESCRIPCION
		
		)
	')
	END
	`,
	`
	IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ripAppWeb].[RESULTADOSCAJAS]') AND type IN (N'P'))
	BEGIN 
	EXEC ('
	CREATE PROCEDURE [ripAppWeb].[RESULTADOSCAJAS] (@FECHA AS DATE, @CAJA AS NVARCHAR(4)) AS 
				
				;WITH CTE_CAJEROS AS (
				SELECT 
					FV.Z
					, FV.CAJA
					, V.NOMVENDEDOR
					, COUNT(*) CANTIDAD
					, ROW_NUMBER() OVER(PARTITION BY FV.Z, FV.CAJA ORDER BY COUNT(*) DESC) POS
				FROM 
					FACTURASVENTA FV 
					INNER JOIN VENDEDORES V ON FV.CODVENDEDOR=V.CODVENDEDOR
				WHERE 
					FV.FECHA=@FECHA
					AND FV.CAJA LIKE @CAJA
				GROUP BY
					FV.Z
					, FV.CAJA
					, V.NOMVENDEDOR)
				, CTE_CAJERO AS (
					SELECT * FROM CTE_CAJEROS WHERE POS=1
				)

				SELECT 
				FECHA, 
				RDW.CAJA+'' (''+ISNULL(C.NOMVENDEDOR,'''')+'')'' CAJA, 
				RDW.Z, 
				CODFORMAPAGO, 
				DESCRIPCION, 
				IMPORTE , 
				ROUND(DECLARADO,2)  DECLARADO, 
				GASTOS GASTOS,
				SERIECAJA,
				FO,
				CERRADO,
				DIFERENCIA ,
				(SELECT TOP 1 CODTIPOPAGO FROM VENCIMFPAGO VP WHERE VP.CODFORMAPAGO=RDW.CODFORMAPAGO) CODTIPOPAGO ,
				''Bs.''+FORMAT(IMPORTE_LOCAL,''n'',''es-VE'') IMPORTE_LOCAL,
				''Bs.''+FORMAT(DECLARADO_LOCAL,''n'',''es-VE'') DECLARADO_LOCAL,
				TASA_VES --,RDW.OBSERVACION
				FROM ripAppWeb.DIFERENCIAFRONT_WEB(@FECHA , @CAJA) RDW 
				LEFT JOIN CTE_CAJERO C ON RDW.SERIECAJA=C.CAJA AND RDW.Z=C.Z
				ORDER BY RDW.CAJA,RDW.Z
	')
	END
	`,
	`
	IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[ripAppWeb].[VERASIENTOCAJA]') AND type IN (N'P'))
BEGIN 
EXEC ('

CREATE PROCEDURE [ripAppWeb].[VERASIENTOCAJA] (
    @FECHA AS DATE,
    @CAJA AS NVARCHAR(4),
    @REDONDEO AS INT,
    @Z AS INT
)
AS
BEGIN
    SET NOCOUNT ON;

    -- Declarar variables para las cuentas de configuración y la consulta dinámica
    DECLARE @CUENTA_SOBRANTE_VENTA AS NVARCHAR(12);
    DECLARE @CUENTA_FALTANTE_VENTA AS NVARCHAR(12);
    DECLARE @CUENTA_SOBRANTE_REDONDEO AS NVARCHAR(12);
    DECLARE @CUENTA_FALTANTE_REDONDEO AS NVARCHAR(12);
    DECLARE @CODMONEDA AS INT;
    DECLARE @CC AS INT = 95;
    DECLARE @SQL NVARCHAR(MAX);
    DECLARE @DB_REMOTE_NAME NVARCHAR(MAX);

    -- Obtener todas las cuentas de configuración y la moneda principal en una sola consulta
    SELECT
        @CUENTA_SOBRANTE_VENTA = SobranteVenta,
        @CUENTA_FALTANTE_VENTA = FaltanteVenta,
        @CUENTA_SOBRANTE_REDONDEO = SobranteRedondeo,
        @CUENTA_FALTANTE_REDONDEO = FaltanteRedondeo
    FROM GENERAL.ripAppWeb.CONFIGURACIONCUENTAS

    SELECT @CODMONEDA = CODMONEDA FROM MONEDAS WHERE PRINCIPAL = ''T'';

    -- Obtener el nombre de la base de datos remota para el servidor vinculado
    SELECT @DB_REMOTE_NAME = BDCONTABLE+ ''.dbo.CUENTAS''
    FROM SERIES S
    INNER JOIN GENERAL.ripAppWeb.EMPRESAUSUARIOS EC ON EC.CODEMPRESACONTABLE  = CAST(SUBSTRING(S.CONTABILIDADB, 6, 3) AS INT) AND EC.EJERCICIO = CAST(SUBSTRING(S.CONTABILIDADB, 2, 4) AS INT)
    WHERE (S.SERIE LIKE ''__'' OR S.SERIE LIKE ''___'') AND S.SERIE LIKE @CAJA;

    -- Construir la consulta principal utilizando SQL dinámico para manejar el OPENQUERY
    SET @SQL = ''
    WITH ASIENTOS_CTE AS (
        -- Cobros del Front
        SELECT 1 AS ORDEN, FECHA, CUENTA, COMENTARIO, DEBE, HABER, CENTROCOSTE, '' + CAST(@CODMONEDA AS NVARCHAR(10)) + '' AS CODMONEDA FROM ripAppWeb.COBROS_FRONT('' + CAST(@REDONDEO AS NVARCHAR(10)) + '', '''''' + CAST(@FECHA AS NVARCHAR(MAX)) + '''''', '''''' + @CAJA + '''''', '' + CAST(@Z AS NVARCHAR(10)) + '', '''''' + @CUENTA_SOBRANTE_VENTA + '''''', '''''' + @CUENTA_FALTANTE_VENTA + '''''')
        
        UNION ALL
        
        -- Ventas
        SELECT 1 AS ORDEN, '''''' + CAST(@FECHA AS NVARCHAR(MAX)) + '''''', CUENTA, COMENTARIO, DEBE, HABER, CENTROCOSTE, '' + CAST(@CODMONEDA AS NVARCHAR(10)) + '' FROM ripAppWeb.VENTAS('' + CAST(@REDONDEO AS NVARCHAR(10)) + '', '''''' + @CAJA + '''''', '' + CAST(@Z AS NVARCHAR(10)) + '')
        
        UNION ALL
        
        -- Costo de Venta
        SELECT 2 AS ORDEN, '''''' + CAST(@FECHA AS NVARCHAR(MAX)) + '''''', CUENTA, COMENTARIO, DEBE, HABER, CENTROCOSTE, '' + CAST(@CODMONEDA AS NVARCHAR(10)) + '' FROM ripAppWeb.COSTOVENTA('' + CAST(@REDONDEO AS NVARCHAR(10)) + '', '''''' + @CAJA + '''''', '' + CAST(@Z AS NVARCHAR(10)) + '')
        
        UNION ALL
        
        -- Impuestos del Front
        SELECT 1 AS ORDEN, FECHA, CUENTA, COMENTARIO, DEBE, HABER, CENTROCOSTE, '' + CAST(@CODMONEDA AS NVARCHAR(10)) + '' FROM ripAppWeb.IMPUESTOSFRONT('' + CAST(@REDONDEO AS NVARCHAR(10)) + '', '''''' + CAST(@FECHA AS NVARCHAR(MAX)) + '''''', '''''' + @CAJA + '''''', '' + CAST(@Z AS NVARCHAR(10)) + '')
    ),
    DIFERENCIAS_CTE AS (
        SELECT
            '''''' + CAST(@FECHA AS NVARCHAR(MAX)) + '''''' AS FECHA,
            CASE
                WHEN SUM(A.DEBE - A.HABER) > 0 THEN '''''' + @CUENTA_FALTANTE_REDONDEO + ''''''
                ELSE '''''' + @CUENTA_SOBRANTE_REDONDEO + ''''''
            END AS CUENTA,
            ''''Diferencia de Redondeo'''' AS COMENTARIO,
            ABS(ROUND(SUM(A.DEBE - A.HABER), '' + CAST(@REDONDEO AS NVARCHAR(10)) + '')) AS DEBE,
            ABS(ROUND(SUM(A.DEBE - A.HABER), '' + CAST(@REDONDEO AS NVARCHAR(10)) + '')) AS HABER,
            NULL AS CENTROCOSTE,
            '' + CAST(@CODMONEDA AS NVARCHAR(10)) + '' AS CODMONEDA,
            1 AS ORDEN
        FROM ASIENTOS_CTE AS A
        WHERE A.CUENTA IS NOT NULL
        HAVING ABS(ROUND(SUM(A.DEBE - A.HABER), '' + CAST(@REDONDEO AS NVARCHAR(10)) + '')) > 0
    )
    
    SELECT
        A.FECHA,
        SUBSTRING('''''' + @CAJA + '''''', 3, 1) AS ASIENTO,
        A.CUENTA,
        C.TITULO,
        '' + CAST(@CC AS NVARCHAR(10)) + '' AS CONCEPTO,
        A.COMENTARIO,
        SUBSTRING('''''' + @CAJA + '''''', 1, 3) AS SERIE,
        '''''''' AS NUMERODOCUMENTO,
        A.DEBE AS DEBE,
        A.HABER AS HABER,
        A.CENTROCOSTE
    FROM
    (
        SELECT ORDEN, FECHA, CUENTA, COMENTARIO, DEBE, HABER, CENTROCOSTE, CODMONEDA FROM ASIENTOS_CTE
        UNION ALL
        SELECT ORDEN, FECHA, CUENTA, COMENTARIO, DEBE, HABER, CENTROCOSTE, CODMONEDA FROM DIFERENCIAS_CTE
    ) A
    INNER JOIN '' + @DB_REMOTE_NAME + '' C ON A.CUENTA COLLATE Modern_Spanish_CI_AS = C.CODIGO
    WHERE
        A.DEBE - A.HABER <> 0
    ORDER BY
        ORDEN, DEBE DESC, HABER DESC;
    '';

    -- Ejecutar la consulta dinámica
    EXEC sp_executesql @SQL;
	--PRINT @SQL

END

')
END
	`

  ]
};