export const QuerysCuentas = 
{
    getAllCuentas:
    `
        SELECT 
            * 
        FROM
            RIP_CONFIGURACIONCUENTAS
    `,
    postAllCuentas:
    `
        DELETE FROM RIP_CONFIGURACIONCUENTAS
        INSERT INTO RIP_CONFIGURACIONCUENTAS(COMISIONBANCARIA,RAIZPAGARE,IVA,FALTANTEVENTA,SOBRANTEVENTA,FALTANTEREDONDEO,SOBRANTEREDONDEO, RAIZUTILIDAD, APERTURA)
        VALUES
       (@COMISIONBANCARIA,@RAIZPAGARE,@IVA,@FALTANTEVENTA,@SOBRANTEVENTA,@FALTANTEREDONDEO,@SOBRANTEREDONDEO, @RAIZUTILIDAD, @APERTURA)

    `

}