export const QuerysCuentas = 
{
    getAllCuentasConfig:
    `
        SELECT 
            FALTANTEVENTA,SOBRANTEVENTA,FALTANTEREDONDEO,SOBRANTEREDONDEO 
        FROM
            RIP_CONFIGURACIONCUENTAS WITH(NOLOCK)
    `,
    postAllCuentas:
    `
        DELETE FROM RIP_CONFIGURACIONCUENTAS
        INSERT INTO RIP_CONFIGURACIONCUENTAS(FALTANTEVENTA,SOBRANTEVENTA,FALTANTEREDONDEO,SOBRANTEREDONDEO)
        VALUES
       (@FALTANTEVENTA,@SOBRANTEVENTA,@FALTANTEREDONDEO,@SOBRANTEREDONDEO)

    `,
    getAllCuentas:
    `
        SELECT CODIGO,TITULO FROM CUENTAS
    `

}