export const QuerysCuentas = 
{
    getAllCuentasConfig:
    `
        SELECT 
            FALTANTEVENTA,SOBRANTEVENTA,FALTANTEREDONDEO,SOBRANTEREDONDEO 
        FROM
           ripAppWeb.CONFIGURACIONCUENTAS WITH(NOLOCK)
    `,
    postAllCuentas:
    `
        DELETE FROM ripAppWeb.CONFIGURACIONCUENTAS
        INSERT INTO ripAppWeb.CONFIGURACIONCUENTAS(FALTANTEVENTA,SOBRANTEVENTA,FALTANTEREDONDEO,SOBRANTEREDONDEO)
        VALUES
       (@FALTANTEVENTA,@SOBRANTEVENTA,@FALTANTEREDONDEO,@SOBRANTEREDONDEO)

    `,
    getAllCuentas:
    `
        SELECT CODIGO,TITULO FROM CUENTAS
    `

}