export const QuerysEmpresas = 
{
  getEmpresaToId:
	`
        DECLARE @CODIGO AS INT;
            SELECT
                EM.CODEMPRESA,
                EM.TITULO,
                SUBSTRING(EM.PATHBD, CHARINDEX(':', EM.PATHBD) + 1, LEN(EM.PATHBD)) AS DB_GESTION
            FROM
                EMPRESAS EM WITH(NOLOCK)
                INNER JOIN EMPRESASUSUARIO EU WITH(NOLOCK) ON EU.CODEMPRESA = EM.CODEMPRESA AND EU.CODUSUARIO = @CODUSUARIO
	`,
    getTiendas:
    `
        SELECT DISTINCT 
            S.SERIE SERIE,
            S.DESCRIPCION DESCRIPCION,
            SUBSTRING(EC.PATHBD, CHARINDEX(':',EC.PATHBD)+1,LEN(EC.PATHBD)) BD
            , ISNULL(SCL.CODCLIENTE,0) CODCLIENTE
            , CAJA.IDFRONT
        FROM
            SERIES S 
            INNER JOIN GENERAL.dbo.EMPRESASCONTABLES EC ON EC.CODIGO=CAST(SUBSTRING(S.CONTABILIDADB,6,3) AS INT) AND EC.EJERCICIO=CAST(SUBSTRING(S.CONTABILIDADB,2,4) AS INT)
            INNER JOIN SERIESCAMPOSLIBRES SCL ON S.SERIE=SCL.SERIE
            INNER JOIN (SELECT RC.IDFRONT, SUBSTRING(RC.SERIEINVENTARIO,1,2) COLLATE Latin1_General_CS_AI SERIE FROM REM_CAJASFRONT RC WHERE CAJAFRONT=1
                    UNION ALL 
                    SELECT 1, SERIE FROM SERIES WHERE SERIE LIKE '___' AND NOT SERIE LIKE '%0%' ) CAJA ON S.SERIE=CAJA.SERIE 
        WHERE
            (S.SERIE LIKE '__' OR S.SERIE LIKE '___')
            AND S.SERIE NOT LIKE 'Z%'
    `,
    getEmpresaContableToId:
    `
       EXEC getEmpresaContableToId @CODUSUARIO, @BD
        
    `
}
