export const QuerysEmpresas = 
{
  getEmpresaToId:
    `
        SELECT DISTINCT 
            CODUSUARIO,
            USUARIO,
            CODEMPRESAGESTION,
            GESTION,
            BDGESTION
        FROM 
            ripAppWeb.EMPRESAUSUARIOS
        WHERE
            CODUSUARIO = @CODUSUARIO
    `,
    getTiendas:
    `
        SELECT DISTINCT 
            S.SERIE SERIE,
            S.DESCRIPCION DESCRIPCION,
            SUBSTRING(EC.PATHBD, CHARINDEX(':',EC.PATHBD)+1,LEN(EC.PATHBD)) BD
            , ISNULL(SCL.CODCLIENTE,0) CODCLIENTE
            , CAJA.IDFRONT
        FROM
            SERIES S 
            INNER JOIN GENERAL.dbo.EMPRESASCONTABLES EC ON EC.CODIGO=CAST(SUBSTRING(S.CONTABILIDADB,6,3) AS INT) AND EC.EJERCICIO=CAST(SUBSTRING(S.CONTABILIDADB,2,4) AS INT)
            LEFT JOIN dbo.SERIESCAMPOSLIBRES SCL ON S.SERIE=SCL.SERIE
            INNER JOIN (SELECT RC.IDFRONT, SUBSTRING(RC.SERIEINVENTARIO,1,2) COLLATE Latin1_General_CS_AI SERIE FROM dbo.  REM_CAJASFRONT RC WHERE CAJAFRONT=1
                    UNION ALL 
                    SELECT 1, SERIE FROM dbo.SERIES WHERE SERIE LIKE '___' AND NOT SERIE LIKE '%0%' ) CAJA ON S.SERIE=CAJA.SERIE 
        WHERE
            (S.SERIE LIKE '__' OR S.SERIE LIKE '___')
            AND S.SERIE NOT LIKE 'Z%'
    `
}
