export const QuerysUser = 
{
    getUserToId:
		`SELECT 
			DISTINCT
			US.USUARIO,
			PM.CODMODULO,
			SPM.CODSUBMODULO
		FROM
			USUARIOS US WITH(NOLOCK)
			INNER JOIN ripAppWeb.PERMISOSMODULOS PM ON PM.CODUSUARIO = US.CODUSUARIO
			LEFT JOIN  ripAppWeb.PERMISOSUBMODULOS SPM ON SPM.CODUSUARIO =  PM.CODUSUARIO AND PM.CODMODULO= SPM.CODMODULO
		WHERE
			US.CODUSUARIO = @CODUSUARIO
			AND PM.ACTIVO = 'T'
			AND ISNULL(SPM.ACTIVO,'T') = 'T'
		`,
	getUserToPass:
	`
		SELECT 
        	US.USUARIO,
        	US.CODUSUARIO
		FROM 
			USUARIOS US WITH(NOLOCK) 
			INNER JOIN RIP_PERMISOSUSUARIOS PU WITH(NOLOCK) ON PU.CODUSUARIO = US.CODUSUARIO
		WHERE 
			US.NEWPASS = @PASS
	`
		
}
