export const QuerysUser = 
{
    getUserToPass:
	`
		SELECT 
        	US.USUARIO,
        	PU.*
		FROM 
			USUARIOS US WITH(NOLOCK) 
			INNER JOIN RIP_PERMISOSUSUARIOS PU WITH(NOLOCK) ON PU.CODUSUARIO = US.CODUSUARIO
		WHERE 
			US.NEWPASS = @PASS
	`
	,getEmpresaToId:
	`
		SELECT 
			EM.CODEMPRESA,
			EM.TITULO,
			SUBSTRING(EM.PATHBD, CHARINDEX(':',EM.PATHBD)+1,LEN(EM.PATHBD)) DB
		FROM 
			EMPRESAS AS EM 
			INNER JOIN EMPRESASUSUARIO AS EU ON EU.CODEMPRESA =  EM.CODEMPRESA AND EU.CODUSUARIO = @CODUSUARIO
	`
}
